### DISCUSSION TITLE
Differential Updates with Zarf Packages

### DISCUSSION THREAD

**Discussion by Racer159** [zarf-dev/zarf#1438] [Ideas]
## Overview

There has been desire in the community to produce differential packages for Zarf updates to ease Day 2 operations and development cycle times.  This discussion is to talk about the potential user flow / implementation for this feature.  Notionally this could look like the following.

## Flow

Given the below future Zarf package configuration (and associated local manifests - see `examples/flux-test` in the Zarf repo):

```yaml
kind: ZarfPackageConfig
metadata:
  name: podinfo-flux
  description: "Deploy flux and then podinfo via flux"
  version: 6.3.3

components:
  - name: flux
    description: "Installs the flux CRDs / controllers to use flux-based deployments in the cluster"
    required: true
    import:
      path: oci://ghcr.io/defenseunicorns/flux:v0.33.0
      name: flux

  - name: podinfo-via-flux
    description: "Example deployment via flux using the famous podinfo example"
    required: true
    manifests:
      - name: podinfo-via-flux
        namespace: podinfo
        files:
          - podinfo-source.yaml
          - podinfo-kustomization.yaml
    repos:
      - https://github.com/stefanprodan/podinfo.git@6.3.3
    images:
      - ghcr.io/stefanprodan/podinfo:6.3.3
    actions:
      onDeploy:
        after:
          # This will use a wait action to wait for the podinfo pods to be ready
          - description: "Podinfo pods to be ready via wait action"
            wait:
              cluster:
                kind: pod
                name: app=podinfo
                namespace: podinfo
                condition: ready
```

You could then run the following:

```bash
zarf package create . --differential oci://ghcr.io/defenseunicorns/podinfo-flux:6.3.2
```

This would pull the `zarf.yaml` layer from the specified OCI-published version and compare each component's oci `import`s first, then it would compose the package and compare the `repo`s, and `image`s and would remove any that were tagged same (while keeping all `chart`s, `file`s, `manifest`s, `actions` and other keys - if an `image` or a `repo` did not have a tag (or sha) it would be retained (i.e. if a full git repo or branch was specified)).

Once finished with that filtering, Zarf would proceed with package create as normal and would create differential Zarf package tarball with a name such as:

```
zarf-package-podinfo-flux-amd64-6.3.3-differential-6.3.2.tar.zst
```

This could also be published to `oci` with:

```bash
zarf package publish zarf-package-podinfo-flux-amd64-6.3.3-differential-6.3.2.tar.zst oci://ghcr.io/defenseunicorns
```

Which would also tag this as a differential package:

```
oci://ghcr.io/defenseunicorns/podinfo-flux:6.3.3-differential-6.3.2
```

If we were to inspect the package we would see that it has a new build key to mark it as `differential`, has the flux key omitted, and has a `differentialMissing` key of all omitted `required` components to display a warning on `zarf package deploy` if a component is not yet in cluster.

```yaml
kind: ZarfPackageConfig
metadata:
  name: podinfo-flux
  description: "Deploy flux and then podinfo via flux"
  version: 6.3.3
build:
  terminal: guilty-spark
  user: wayne
  architecture: amd64
  differential: true
  differentialMissing:
  - flux
  timestamp: Tue, 14 Mar 2023 18:05:48 -0500
  version: v0.26.0
  migrations:
  - scripts-to-actions

components:
  - name: podinfo-via-flux
    description: "Example deployment via flux using the famous podinfo example"
    required: true
    manifests:
      - name: podinfo-via-flux
        namespace: podinfo
        files:
          - podinfo-source.yaml
          - podinfo-kustomization.yaml
    repos:
      - https://github.com/stefanprodan/podinfo.git@6.3.3
    images:
      - ghcr.io/stefanprodan/podinfo:6.3.3
    actions:
      onDeploy:
        after:
          # This will use a wait action to wait for the podinfo pods to be ready
          - description: "Podinfo pods to be ready via wait action"
            wait:
              cluster:
                kind: pod
                name: app=podinfo
                namespace: podinfo
                condition: ready
```

## Notes

> ⚠️ **NOTE:** - the package examples provided assume that #1060 has been completed as a pre-req

> ⚠️ **NOTE:** - in the above implementation you would be prevented from composing a differential since (as proposed in #1060) skeleton packages are not the same as full packages:

```yaml
# The following would not be possible - you cannot publish differential skeleton (composable) packages
components:
  - name: flux
    description: "Installs the flux CRDs / controllers to use flux-based deployments in the cluster"
    required: true
    import:
      path: oci://ghcr.io/defenseunicorns/flux:v0.33.0-differential-v0.32.0
      name: flux
```

> ⚠️ **NOTE:** - we would need to add a key denoting where a component was imported from since this information is removed when packages are built currently.

> ⚠️ **NOTE:** - when importing components it is possible to override/merge keys, if other keys were specified other than import we would likely need to keep that import (even if it were the same tag) and build it into the package - we could likely perform `image` and `repo` filtering for this however.

> ⚠️ **NOTE:** - matching would be done on component names and ordering - iterating through the new component list (NEW), and matching that against the pulled OCI `zarf.yaml` component list (OLD).  If the new list had components not in the old one those would always be included, and if the old one had components not in the new list those would be skipped.

```
# Given the following oci-imported and regular components
## NEW
oci://ghcr.io/defenseunicorns/flux:v0.33.0
oci://ghcr.io/defenseunicorns/other:v0.1.0
podinfo

## OLD
oci://ghcr.io/defenseunicorns/flux:v0.33.0
oci://ghcr.io/defenseunicorns/hello:v0.2.1
podinfo
world

## RESULT
oci://ghcr.io/defenseunicorns/other:v0.1.0
podinfo
```

```
# Given an order change the following would result (since podinfo is found before flux)
## NEW
oci://ghcr.io/defenseunicorns/other:v0.1.0
podinfo
oci://ghcr.io/defenseunicorns/flux:v0.33.0

## OLD
oci://ghcr.io/defenseunicorns/flux:v0.33.0
oci://ghcr.io/defenseunicorns/hello:v0.2.1
podinfo
world

## RESULT
oci://ghcr.io/defenseunicorns/other:v0.1.0
podinfo
oci://ghcr.io/defenseunicorns/flux:v0.33.0
```

> ⚠️ **NOTE:** - this does not help with differential updates for `dataInjection`s (which could also be large)
