### DISCUSSION TITLE
v0.13.1

### DISCUSSION THREAD

**Discussion by RothAndrew** [zarf-dev/zarf#161] [Announcements]
⚠️ Contains breaking changes

[Until we finish migrating from Repo1 to GitHub the release artifacts can be found HERE](https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/releases/v0.13.1).

### ⚠️ BREAKING: The private container registry that `zarf init` deploys now requires auth

Packages will need to include `imagePullSecrets:` in their pod manifests and a corresponding regcred. See [the Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) for more information. Using the special string `###ZARF_DOCKERAUTH###` in your manifests will be automatically picked up by Zarf during `package deploy` and replaced with a properly formatted auth string, which is the base64 encoded `username:password`

Here's an example of a valid Secret manifest for images that originated from Registry1 or DockerHub (K3s automatically redirects them to the private registry):

```yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: private-registry
  namespace: my-cool-app
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry1.dso.mil": {
          "auth":"###ZARF_DOCKERAUTH###"
        },
        "docker.io": {
          "auth":"###ZARF_DOCKERAUTH###"
        }
      }
    }
```

### Deploy remote packages

Now you can run `zarf package deploy` on remote packages.

Example:

```bash
# Naughty way
zarf package deploy https://example.com/some-package.tar.zst --insecure

# Good way
zarf package deploy https://example.com/some-package.tar.zst --shasum 15h1oi2h5ni1o2y5iunb1t25bui1t25gnu12n5
```

### Full Changelog

Note: The v0.13.0 release was aborted due to a missing credential in the release pipeline. This release replaces v0.13.0 with the only change being referencing the new credential in the release pipeline yaml. We do it this way because we believe artifacts should be immutable.

* #93 - Add E2E test framework with Terratest
* #91 - Simplify the Vagrant workflow when running the examples
* #94 - Add framework for GitHub Actions with pull request chatops dispatching
* #95 - Integrate the E2E tests with the GitHub Actions pipeline
* #103 - Add Contributor Guide
* #104 - Roll back changes to the Big Bang example NetworkPolicy CIDRs for better demo compatibility
* #106 & #110 - Add more E2E tests
* #112 - Add `pre-commit` hooks
* #98 - Beginnings of an overhaul on the repo's documentation
* #116 - Add `zarf version` command
* #117 - Fix the Makefiles for compatibility with M1 Macs
* #111 - Update the version of `kubescape` in the Big Bang Core example
* #124 - Add "Get Started" documentation for running the Doom game example
* #126 - Update Helm library to v3.7.0
* #107 - Add check to make sure all components passed in `--components` flag exist
* #135 - Add Zarf Components documentation
* #128 - Add check for illegal characters in entered hostnames
* #139 - Add flag for setting the log level
* #147 - Unify to one `go.mod` to make VS Code happy
* #151 - Run `pre-commit run -a` an the codebase
* #143 - Add ability to deploy remote packages
* #157 - Add Logging documentation
* #156 - Remove unnecessary logging package and set log level in root
* #158 - Update GitHub Actions pipeline to use the new robot account for Registry1
* #144 - Add authentication to utility registry
* #160 - Fix the GitLab release pipeline

<hr /><em>This discussion was created from the release <a href='https://github.com/defenseunicorns/zarf/releases/tag/v0.13.1'>v0.13.1</a>.</em>
