### DISCUSSION TITLE
Available options for Zarf's image search functionality

### DISCUSSION THREAD

**Discussion by alita1991** [zarf-dev/zarf#2061] [Q&A]
As a zarf user, it would be wonderful to understand if there are other ways to find images in the helm charts besides rendering the chart. This is very important because I want to improve the current solution I have to find images in operators, where I basically define a dummy deployment file with 0 replicas to help zarf find the image.

If this is already documented somewhere, a link to the documentation can also help.

Thanks

**Comment by Racer159** [comment]
Currently there isn't a better way to do this though we have thought about things like spinning up a deployment in a throw away cluster to detect the pods that come up - https://github.com/defenseunicorns/zarf/issues/1277 - that implementation will require more thought / time though

**Comment by a1994sc** [comment]
Not super sure if this should be a separate discussion, however it would be nice if we could add annotations or something to give `zarf` hints on how to find images from things that are not deployment/statefulset/daemonsets ... 

Like with in a CRD, example Crossplane provider:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-keycloak
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-keycloak:v0.6.0
```

So annotation of

```yaml
  annotations:
    zarf.dev/hint: ".spec.package"
```

In that example I just use a similar syntax of `yq` to specific the path in the crd to find the image.
