### DISCUSSION TITLE
v0.11.0

### DISCUSSION THREAD

**Discussion by RothAndrew** [zarf-dev/zarf#88] [Announcements]
## What's Changed

New examples and an update to the zarf.yaml schema

⚠️  Contains breaking changes

### New Example: Postgres Operator

A new example is available that creates a Zarf package that will deploy an example of a mostly production-ready Postgres database using Zarf's Applicance Mode. It comes with high availability, point-in-time backups, and periodic full backups. Comes with PGAdmin as a good demo of the proof of concept. Uses Zalando's [postgres-operator](https://github.com/zalando/postgres-operator)

### New Example: Big Bang Core

A new example is available that creates a Zarf package that will deploy Big Bang Core to a Utility Cluster. This isn't normally the way you'd utilize a Utility Cluster, but it makes for a great easy to run demo. In a production scenario you would typically deploy a utility cluster separately from your main production workload cluster.

### ⚠️ BREAKING: New schema for `zarf.yaml` config

The schema for the `zarf.yaml` config file has changed to allow optional components in Zarf deploy packages just like you can do in a Zarf init package

Previous:
```yaml
kind: ZarfPackageConfig
metadata:
  name: foo
  description: "Foo example"

local:
  manifests: manifests

  files:
    - source: https://example.com/foo
      target: "/usr/local/bin/foo"
      shasum: 52299bd5a2df28b6a6ff9926e09abd0fa5e6c1094f5bb75b036a0452cfc00dfa
      executable: true

  images:
    - registry1.dso.mil/ironbank/big-bang/base:8.4

remote:
  repos:
    - https://repo1.dso.mil/platform-one/big-bang/foo.git@1.2.3

  images:
    - registry1.dso.mil/ironbank/big-bang/base:8.4
```

New:
```yaml
kind: ZarfPackageConfig
metadata:
  name: foo
  description: "Foo example"

components:
  - name: baseline
    required: true
    manifests: manifests
    images:
      - registry1.dso.mil/ironbank/big-bang/base:8.4

  - name: optional-feature
    required: false
    default: true
    files:
      - source: https://example.com/foo
         target: "/usr/local/bin/foo"
         shasum: 52299bd5a2df28b6a6ff9926e09abd0fa5e6c1094f5bb75b036a0452cfc00dfa
         executable: true

utilityCluster:
  repos:
    - https://repo1.dso.mil/platform-one/big-bang/foo.git@1.2.3

  images:
    - registry1.dso.mil/ironbank/big-bang/base:8.4
```

## Full changelog

- Add Postgres Operator Example (#50)
- Add backups to postgres-operator example (#52)
- Add Big Bang Core Example (#29)
- Fix makefile for postgres-operator example (#54)
- Update kafka tools URL (#57)
- Add resource requests and limits to Utility Cluster deployments (#59)
- Misc refactoring and cleanup (#61)
- Update Big Bang Core example with kubescape remediations (#62)
- Add kubescape to Big Bang Core example package (#60)
- Implement SHA256SUM validation (#65)
- Add zarf prepare sha256sum URL arg for remote SHASUM (#69)
- Upgrade Big Bang Core example to BB v1.17.0 (#67)
- BREAKING: Restructure zarf config yaml (#71)
- Docs and refactors for better kubescape scanning of BB example (#80)

**Compare**: https://github.com/defenseunicorns/zarf/compare/v0.10.4...v0.11.0

<hr /><em>This discussion was created from the release <a href='https://github.com/defenseunicorns/zarf/releases/tag/v0.11.0'>v0.11.0</a>.</em>
