### DISCUSSION TITLE
v0.12.0

### DISCUSSION THREAD

**Discussion by RothAndrew** [zarf-dev/zarf#90] [Announcements]
## What's Changed

`zarf init` Now always installs the private Docker registry.

:warning: Contains breaking changes

[Until we finish migrating from Repo1 to GitHub the release artifacts can be found HERE](https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/releases/v0.12.0).

### ⚠️ BREAKING: New schema for `zarf.yaml` config

The schema for the `zarf.yaml` config file has changed. It has been simplified now that the docker registry is always present, there's no need for making a distinction between local and remote images. They are now all what used to be called "remote".

New:
```yaml
kind: ZarfPackageConfig
metadata:
  name: foo
  description: "Foo example"

components:
  - name: baseline
    required: true
    manifests: manifests
    repos:
      - https://repo1.dso.mil/platform-one/big-bang/foo.git@1.2.3
    images:
      - registry1.dso.mil/ironbank/big-bang/base:8.4

  - name: optional-feature
    required: false
    default: true
    files:
      - source: https://example.com/foo
        shasum: 52299bd5a2df28b6a6ff9926e09abd0fa5e6c1094f5bb75b036a0452cfc00dfa
        target: "/usr/local/bin/foo"
        executable: true
```

Previous:

```yaml
kind: ZarfPackageConfig
metadata:
  name: foo
  description: "Foo example"

components:
  - name: baseline
    required: true
    manifests: manifests
    images:
      - registry1.dso.mil/ironbank/big-bang/base:8.4

  - name: optional-feature
    required: false
    default: true
    files:
      - source: https://example.com/foo
        target: "/usr/local/bin/foo"
        shasum: 52299bd5a2df28b6a6ff9926e09abd0fa5e6c1094f5bb75b036a0452cfc00dfa
        executable: true

utilityCluster:
  repos:
    - https://repo1.dso.mil/platform-one/big-bang/foo.git@1.2.3

  images:
    - registry1.dso.mil/ironbank/big-bang/base:8.4
```

### Full Changelog

* Change zarf init to always install the docker registry by @jeff-mccoy in https://github.com/defenseunicorns/zarf/pull/82
    * Fix #83 by switching from `zarf.localhost` to `127.0.0.1` as the internal endpoint for the docker registry and Gitea
    * Update golang imports from the old Repo1 location to the new GitHub one
    * Update go deps versions
    * Rename the 3rd init option from `utility-cluster` to `gitops-service`

**Compare**: https://github.com/defenseunicorns/zarf/compare/v0.11.0...v0.12.0
