### ISSUE TITLE
Use variables for Zarf package remove

### ISSUE THREAD

**Issue by UncleGedd** [zarf-dev/zarf#1801]
### Is your feature request related to a problem? Please describe.
I'd like to have more control over the remove cycle of Zarf packages through the use of variables. 

For example, I need to control the deletion of a KMS key that encrypts an S3 bucket based on the "force delete" config of the S3 bucket, noting that the "force delete" config is set as a Zarf variable during package deployment.

### Describe the solution you'd like
Given a `zarf-config.yaml` I'd like to add variables to be used during the remove, for example something like:
```
package:
  deploy:
    set:
      foo: bar
  remove: 
    set:
      foo: baz
```
And then I'd like to use `ZARF_VAR_FOO` in an onRemove action
