### ISSUE TITLE
Zarf capability to publish a package container images and charts to an OCI registry

### ISSUE THREAD

**Issue by laurentiusoica** [zarf-dev/zarf#1830]
I have the following use case:

When in online environments, I use ArgoCD for CD and GitOps. I have an external Git Repository with the desired state of the environment, and then an external OCI registry from where the container images and helm charts are served for ArgoCD to reconcile the state.

Now I have to support air gapped environments as well. For some environments, there is a Git Server and an OCI registry already available, for others, I have to bring my own. I would like to converge the online and offline environments as soon as I have the ArgoCD component up and running. In order to have ArgoCD up, I have to:

- build at home the package with:
-- optional infra provisioning scripts (when there is no K8S available)
-- the Git Repository
-- container images
-- helm charts
- move the package to the air-gapped environment
- optional infra provisioning
- optional git server and OCI registry provisioning
- push the Git Repository to the Git Server (that could be external or provisioned by me in a previous step)
- push the Container Images to the OCI registry (that could be external or provisioned by me in a previous step)
- push the Helm Charts to the OCI registry (that could be external or provisioned by me in a previous step)
- deploy ArgoCD (as I have now both the charts and container images available)
- bind ArgoCD to the Git Repository
- from there on, the airgap flow converges with the online flow 

As far as I was able to understand so far, Zarf is a great fit for the packaging step. By providing Zarf with the following config:
```
kind: ZarfPackageConfig
metadata:
  name: name
  description: product package
  version: 0.0.10
components:
- name: infraprovisioning
  description: Scripts required for infra provisioning
  files:
      - source: 
        target: 
- name: gitops-repository
  description: Environment definition repository
  repos:
  - https://<some git repo>.git
- name: somecomponent
  description: somecomponent
  charts:
  - name: chartname
    url: oci://<chart url>
    version: 1.2.3
  images:
  - <OCI image>
  - <OCI image>
  - <OCI image>
- name: someothercomponent
  description: someothercomponent
  charts:
  - name: chartname
    url: oci://<chart url>
    version: 1.2.3
  images:
  - <OCI image>
  - <OCI image>
```

zarf create will download everything and build the package for me.
But now, as soon as I have the package available into the target airgapped environment, I don't have the corresponding zarf actions to publish everything into the stores available in the airgap environment.

### Describe the solution you'd like
CLI or library APIs that takes a package and just publish it's content into the target stores, e.g.:
```
zarf package publish-images --registry-url <target OCI registry>
zarf package publish-charts --registry-url <target OCI registry>
zarf package publish-git-repositories --git-url <git server url>
```
I guess the last one is similar in functionality with:
```
zarf package deploy --components=gitops-repository
```
