### ISSUE TITLE
Zarf file os/arch matrix support

### ISSUE THREAD

**Issue by Racer159** [zarf-dev/zarf#1925]
### Is your feature request related to a problem? Please describe.
Zarf should support the addition of new keys to make the use of binaries easier with less copy / paste.

### Describe the solution you'd like

- **Given** I have a package that needs to pull in multiple files for different OSes and architectures
- **When** I specify the `matrix` key on my `file`
- **Then** Zarf will pull all of the files in the matrix and load the correct file per the local os/arch that zarf is run with

i.e.:

```yaml
kind: ZarfPackageConfig
metadata:
  name: k3d

components:
  - name: k3d
    required: true
    files:
      - source: https://github.com/k3d-io/k3d/releases/download/v5.5.1/k3d-###ZARF_MATRIX_OS###-###ZARF_MATRIX_ARCH######ZARF_MATRIX_EXE_SHIM###
        target: ~/.zarf/bin/k3d
        matrix:
          os: ["darwin", "linux", "windows"]
          arch: ["amd64", "arm64"]
          shasums: 
            darwin-amd64: 5d3b6776eb349eab3829229ce8c87f9c279093b0272cc522981e101b40c4d6c4
            darwin-arm64: 891161cd18f5505c8d3eff08344c00ca76f807dfb3d019d119fc1013fe3616ef
            linux-amd64: 4849027dc5e835bcce49070af3f4eeeaada81d96bce49a8b89904832a0c3c2c0
            linux-arm64: 4a3740fb2bc61fda32b2437c270a5f7dc321ade5e9cb6d932b4b97397538042d
            windows-amd64: ba8cf49fa6d3a19771e5837a2913a86cceaa70d79189d2f87d6f9967ca3e8f1b
        executable: true
```

### Describe alternatives you've considered
We could do this at the component level instead but that would require actions, manifests or other reusable resources to be duplicated across those components.

### Additional context
This will be part of what will help address patterns like this:  https://github.com/defenseunicorns/uds-package-dubbd/blob/main/defense-unicorns-distro/zarf.yaml#L138
This also follows patterns like: https://docs.github.com/en/actions/learn-github-actions/expressions
