### ISSUE TITLE
Allow Option for Charts to be stored not deployed

### ISSUE THREAD

**Issue by shanewhite97** [zarf-dev/zarf#2114]
### Is your feature request related to a problem? Please describe.

I am trying to package up charts, repos and images, so that when I deploy to my offline cluster, I can access those charts and deploy through flux.

So far the repos are fine and they get mutated as expected, but charts seem to auto deploy rather than being stored in a registry or gitea.

### Describe the solution you'd like

- **Given** that I am packing a zarf solution containing charts
- **When** When the package is deployed
- **Then** I'd like it to store the charts somewhere that can then be referenced by a flux repo and consumed

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

I am currently trying to put them in a git repo and referencing that to workaround it

**Comment by Shane-UE** [comment]
https://github.com/defenseunicorns/zarf/issues/1092

Might be similar to this

**Comment by Racer159** [comment]
The flux side of this is partially in https://github.com/defenseunicorns/zarf/pull/2005 though that is currently blocked by https://github.com/fluxcd/source-controller/issues/807 for the internal Zarf registry since that is served over http

The other side of mirroring oci artifacts is possible under the `images` key as of v0.30.1

**Comment by Shane-UE** [comment]
What about if the chart is not an oci artifact? We are currently just using bog standard helm charts

**Comment by Racer159** [comment]
Currently that's not supported but we could consider implementing changes / accommodating expansion into this in https://github.com/defenseunicorns/zarf/issues/2245 - right now `charts` is very geared toward deploying them into your cluster so we'd need to design a mechanism to not do that.  _Technically_ you can use the `helm` CLI and `files` in zarf to do whatever you want.  I experimented with driving docker and docker images directly in my `k3d` package: https://github.com/Racer159/zarf-package-k3d

**Comment by danieljmehler** [comment]
I had to do something similar recently, where we didn't want to deploy our Zarf package, just mirror-resources. The `zarf package mirror-resources` works great for adding packaged git repos to the Zarf gitea and images to the Zarf registry, but for Helm charts, we did the following (simplified version):

1. Create `zarf.yaml`:

    ```yaml
    kind: ZarfPackageConfig
    metadata:
      name: metallb
      version: 0.14.4
      description: |
        A Zarf Package that deploys MetalLB

    variables: []

    components:
      - name: metallb
        description: |
          Deploys MetalLB
        required: true
        charts:
          - name: metallb
            url: https://metallb.github.io/metallb
            version: 0.14.4
            namespace: metallb
        images:
          - quay.io/metallb/controller:v0.14.4
          - quay.io/metallb/speaker:v0.14.4
    ```

1. Create Zarf package:

    ```bash
    zarf package create
    ```

1. Transfer to airgap.

1. Mirror resources to load images into registry:

    ```bash
    zarf package mirror-resources zarf-package-metallb-amd64-0.14.4.tar.zst \
        --registry-url 127.0.0.1:31999 \
        --registry-push-username zarf-push \
        --registry-push-password <generated-registry-push-password> \
        --git-url http://zarf-gitea-http.zarf.svc.cluster.local:3000 \
        --git-push-username zarf-git-user \
        --git-push-password <generated-git-push-password>
    ```

1. Use Helm to push MetalLB chart to Zarf registry using OCI protocol:

    ```bash
    # Create tempdir for workspace
    TEMPDIR=$(mktemp -d)
    # Decompress zarf package to tmpdir
    zarf tools archiver decompress zarf-package-metallb-amd64-0.14.4.tar.zst $TEMPDIR
    # Zarf puts Helm charts in a "components" dir named "<.components[].name>.tar"
    # (I'm assuming on how the .tar file is named...).
    # Untarring "./components/metallb.tar" unpacks the gzipped Helm chart
    # at "./components/metallb/charts/metallb-0.14.4.tgz"
    tar xvf ${TEMPDIR}/components/metallb.tar -C ${TEMPDIR}/components
    # Use Helm push
    helm push ${TEMPDIR}/components/metallb/charts/metallb-0.14.4.tgz --plain-http oci://127.0.0.1:31999/helm
    ```

    To download the chart: `helm pull --plain-http oci://127.0.0.1:31999/helm/metallb --version 0.14.0`

Of course, this doesn't get around the [rke2 HelmChart](https://docs.rke2.io/helm#using-the-helm-crd) not being able to use OCI registries with HTTP (and presumably flux), but it at least allows you to do some automation to load the Helm chart into a registry for storage and access using the helm binary.
