### ISSUE TITLE
Using local image archives no longer works

### ISSUE THREAD

**Issue by rjferguson21** [zarf-dev/zarf#2181]
### Environment
Device and OS: Linux 
App version: v0.31.0
Kubernetes distro being used: k3d
Other:

### Steps to reproduce
1.  Create an image archive locally with `docker save busybox -o busybox.tar`
2.  Create a zarf.yaml that references the archive in the `images:` list for a component.

```
kind: ZarfPackageConfig
metadata:
  name: example
  description: Test component
  version: 1.0.0

components:
  - name: zebra
    description: "This is a zebra and they have stripes"
    images:
      - "/home/rob/busybox.tar"
```

3.  `zarf package create . --confirm`

### Expected result
A package to  be created that includes the referenced image archive.

### Actual Result
Error indicating the package create has failed.  
```
     ERROR:  Failed to create package: failed to create ref for image /home/rob/busybox.tar: invalid reference
             format
```

### Visual Proof (screenshots, videos, text, etc)
![2023-12-07_17-12-1701991967](https://github.com/defenseunicorns/zarf/assets/1746282/559d4ebd-254d-43d8-86a1-c540fe179d9c)

### Severity/Priority
Not critical

### Additional Context
Originally added in https://github.com/defenseunicorns/zarf/pull/1173,
