### ISSUE TITLE
Importing BigBang component does not allow overriding of BigBang version

### ISSUE THREAD

**Issue by ragingpastry** [zarf-dev/zarf#2465]
### Environment
Device and OS:
App version:
Kubernetes distro being used:
Other:

It appears that you cannot override the `version` of the BigBang extension when importing
### Steps to reproduce
```
#!/usr/bin/env bash

mkdir -p development
mkdir -p base

cat << EOF > development/zarf.yaml
kind: ZarfPackageConfig
metadata:
  name: "bigbang-development"
  yolo: true
components:
  - name: bigbang
    required: true
    import:
      path: ../base
      name: bigbang
    extensions:
      bigbang:
        version: "2.24.0"
EOF

cat << EOF > base/zarf.yaml
kind: ZarfPackageConfig
metadata:
  name: "Base BigBang"
components:
  - name: bigbang
    required: true
    extensions:
      bigbang:
        version: "2.25.0"
EOF

(cd development; echo "n" | zarf package create --no-progress --no-color . 2>&1 | grep extensions -A 3)
```

### Expected result
```
  extensions:
    bigbang:
      version: 2.24.0
      repo: https://repo1.dso.mil/big-bang/bigbang.git
```

### Actual Result
```
  extensions:
    bigbang:
      version: 2.25.0
      repo: https://repo1.dso.mil/big-bang/bigbang.git
```

### Additional Context
The workaround is just to use zarf variables, but it would be nice to not need to do that.
