### ISSUE TITLE
helm override variables are limited to strings

### ISSUE THREAD

**Issue by Michael-Kruggel** [zarf-dev/zarf#2783]
### Steps to reproduce
1. Add helm override variable to component
2. Set that variable to something other than a string (e.g an array) in the zarf config
3. Deploy package using said config

### Expected result
Value of variable is set in chart values

### Actual Result
No value is set, chart's default value is used

### Visual Proof (screenshots, videos, text, etc)
Example `zarf.yaml` component:

```yaml
components:
  - name: jenkins
    required: true
    charts:
      - name: jenkins
        namespace: jenkins
        url: https://charts.jenkins.io
        version: 5.4.3
        repoName: jenkins
        releaseName: jenkins
        valuesFiles:
          - ../values/common.yaml
        variables:
          - name: JENKINS_PLUGINS
            description: "List of plugins to install on Jenkins startup"
            path: controller.installPlugins
```

Example `zarf-config.yaml`:

```yaml
package:
  deploy:
    components: 'jenkins'
    set:
      jenkins_plugins:
        - kubernetes:4238.v41b_3ef14a_5d8
        - workflow-aggregator:596.v8c21c963d92d
        - git:5.2.2
        - configuration-as-code:1810.v9b_c30a_249a_4c
        - oic-auth:4.269.va_7526f34f306
        - prometheus:773.v3b_62d8178eec
        - cloudbees-disk-usage-simple:203.v3f46a_7462b_1a_
        - saml:4.464.vea_cb_75d7f5e0
```

Values in k9s:
![image](https://github.com/user-attachments/assets/e9ce8593-f8b3-4921-8bdc-3f943aee6133)

**Comment by Racer159** [comment]
This is relatively simple to accomplish internally to Zarf by changing `string` to `interface{}` on the SetVariables field _however_ the wall this is effectively blocked on (https://github.com/spf13/viper/issues/1014) would need a workaround like what UDS CLI has done: https://github.com/defenseunicorns/uds-cli/blob/main/src/cmd/root.go#L151 (which as-written there only supports YAML) or would need to swap around libraries to something else.

**Comment by Racer159** [comment]
The bright side is that Zarf does not process config files like this:

```yaml
package:
  deploy:
    set:
      test:
        aT: thingT
        bT: to-beT
```

so it would be easier to stay away from making this a breaking change.
