### ISSUE TITLE
Wildcards when support using K8s manifests

### ISSUE THREAD

**Issue by jastBytes** [zarf-dev/zarf#2814]
### Is your feature request related to a problem? Please describe.
It is pretty exhausting to specify many K8s manifests in the `zarf.yaml`. I end up using `find` to get all paths together.

### Describe the solution you'd like

- **Given** you have a folder called `manifests` with all K8s manifests relative to your `zarf.yaml`
- **When** you secify the following in your `zarf.yaml`:
```yaml
components:
  - name: manifests
    required: true
    manifests:
      - name: manifests
        namespace: default
        files:
          - manifests/**/*.yaml
```
- **Then** all files with extension `.yaml` within `manifests` and all of it's subfolders should be in the package on create.
