### ISSUE TITLE
Warnings are suppressed in v0.38.2

### ISSUE THREAD

**Issue by bcvanmeurs** [zarf-dev/zarf#2907]
### Environment
Device and OS: macOS arm version
App version: v0.38.*
Kubernetes distro being used: kind latest
Other:

### Steps to reproduce
1. create a package with a deployment that depends on CRDs
2. deploy the package on a fresh kind cluster

This made it very hard to debug the deployment, I could not figure out why the deployment was going wrong.

<details><summary>zarf.yaml</summary>

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/zarf/v0.37.0/zarf.schema.json
kind: ZarfPackageConfig
metadata:
  name: package
  version: 0.0.0
  description: |
    A Zarf Package

components:
  - name: dcgm-exporter
    description: |
      Deploys the dcgm-exporter for GPU workloads metrics
    required: true
    charts:
      - name: dcgm-exporter
        url: https://nvidia.github.io/dcgm-exporter/helm-charts
        version: 3.5.0
        namespace: dcgm-exporter
        valuesFiles:
          - dcgm-exporter/dcgm-exporter-values.yaml

    images:
      - nvcr.io/nvidia/k8s/dcgm-exporter:3.3.7-3.5.0-ubuntu22.04
```
</details> 

### Expected result
as in v0.37.0:
<img width="834" alt="image" src="https://github.com/user-attachments/assets/c486f754-e6d2-4c01-b9e8-61c61e679d29">

### Actual Result
in v0.38.2:
<img width="811" alt="image" src="https://github.com/user-attachments/assets/27b2e377-cc12-4750-b860-ff109910ca85">
This made it very hard to debug the deployment, I could not figure out why the deployment was going wrong.
Also I could not find any option to surface warnings, setting different log levels did not make a difference.

### Additional Context
Add any other context or screenshots about the technical debt here.
