### ISSUE TITLE
Add the ability to pass a file as a var or argument for components

### ISSUE THREAD

**Issue by rdecuir** [zarf-dev/zarf#2931]
### Is your feature request related to a problem? Please describe.

I have a list of images that I want to be in the internal registry in zarf. I build the `zarf.yaml `with a component with this huge list of images, but would like to reduce the size of the `zarf.yaml` itself. 

I would like to be able to create a file called `app-images.yaml`  ex below, and the reference this file as a var or argument for zarf to use under the component.

`app-images.yaml`
```
images:
- docker.io/libray/nginx:latest
- docker.io/libray/alpine:latest
```

`zarf.yaml`
```
# I know this doesnt work just trying to show what i would like to do
constants:
- name: APP_IMAGES
  value: {{ readYaml 'app-images.yaml' }}

components:
- name: app-images
  images: ### APP_IMAGES ### 
```

### Describe the solution you'd like
I would like to see a way to pass a yaml file as a var or as some argument to the component to reduce the "size" of the zarf.yaml for readability.
