### ISSUE TITLE
Enable linting ignored

### ISSUE THREAD

**Issue by phillebaba** [zarf-dev/zarf#2949]
We should explicitly check for all errors. This means never using blank identifiers for returned errors nor not capturing any errors.

The check should be enabled in the linter and all warnings should be fixed.

```yaml
linters-settings:
    errcheck:
        check-blank: true
issues:
    include:
        - EXC0001

```
