### ISSUE TITLE
Helm overrides omitted when component is imported

### ISSUE THREAD

**Issue by rjferguson21** [zarf-dev/zarf#2966]
### Environment
Device and OS: Linux 
App version: v0.38.3
Kubernetes distro being used: N/A
Other:

### Steps to reproduce
1.  Create a `a/zarf.yaml`
```
kind: ZarfPackageConfig
metadata:
  name: a
  description: example package A
  version: 0.0.1
components:
  - name: foo
    required: false
    default: true
    charts:
      - name: podinfo-compose
        version: 6.4.0
        url: oci://ghcr.io/stefanprodan/charts/podinfo
        namespace: podinfo-override
        releaseName: podinfo-override
```
2. Create `b/zarf.yaml` which imports `foo` component from a/zarf.yaml and also contains helm override variables
```
kind: ZarfPackageConfig
metadata:
  name: b
  description: example package B
  version: 0.0.1
components:
  - name: foo
    import:
      path: ../a
    charts:
      - name: podinfo-compose
        variables:
          - name: B_COLOR
            description: color of component B
            path: color
```
3.   `cd b && zarf package create .`

### Expected result
The component foo contains a chart named `podinfo-compose` that includes the Helm override variables including `B_COLOR`
```
- name: foo
  charts:
  - name: podinfo-compose
    version: 6.4.0
    url: oci://ghcr.io/stefanprodan/charts/podinfo
    namespace: podinfo-override
    releaseName: podinfo-override
    variables:
    - name: B_COLOR
      description: color of component B
      path: color
```      
### Actual Result
The component foo contains the Helm chart but is missing any variables defined in `b/zarf.yaml`, including `B_COLOR`

### Visual Proof (screenshots, videos, text, etc)
![2024-09-04_16-09-1725483948](https://github.com/user-attachments/assets/d0189a03-dc8d-485c-9c3c-91e9880aa27a)

### Severity/Priority
Medium 

### Additional Context
We've been experimenting using Helm overrides at the Zarf layer in UDS Core and would like to push some of our bundle level variables into Zarf vars to ensure a consistent interface for consumers of UDS Core who generally are consuming the uds-core package.
