### ISSUE TITLE
Remove hints from printed yaml

### ISSUE THREAD

**Issue by AustinAbro321** [zarf-dev/zarf#2974]
### Is your feature request related to a problem? Please describe.
Currently when we print a package on create or on deploy we add hints to the printed yaml. There is a bug with how the hints are displayed which can be seen below. Variables are both a sub-key on charts and a key on the top level package key so the hint for variables the package level key shows up on variables the subkey on charts. 

The feedback I've received from users, and that I personally agree with, is that these hints don't add much, and they would rather just get the package. While we could fix the variables issue, I would rather remove the hints all together. 

```yaml
kind: ZarfPackageConfig

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
metadata:  information about this package

  name: helm-charts
  description: Example showcasing multiple ways to deploy helm charts
  version: 0.0.1
  architecture: amd64

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
components:  components selected for this operation

- name: demo-helm-charts
  required: true
  charts:
  - name: podinfo-local
    version: 6.4.0
    localPath: chart
    namespace: podinfo-from-local-chart
    valuesFiles:
    - values.yaml
    
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
variables:  deployment-specific values that are set on each package deployment
    - name: REPLICA_COUNT
      description: Override the number of pod replicas
      path: replicaCount
  - name: podinfo-oci
    version: 6.4.0
    url: oci://ghcr.io/stefanprodan/charts/podinfo
    namespace: podinfo-from-oci
    valuesFiles:
    - values.yaml
```

### Alternatives considered
I've considered removing the print yaml of the package all together, however it may be useful to those deploying, and those who use compose and package templates.
