### ISSUE TITLE
Support helm --skip-schema-validation for values.schema.json that has references to the internet

### ISSUE THREAD

**Issue by jomeier** [zarf-dev/zarf#3118]
Hi,
I fail on creating a Zarf package for the Dagster Pipeline Orchestrator.
The Helm Chart of Dagster uses a values.schema.json file, that has a reference to the internet.
Because of that, the deployment of my Dagster Zarf package fails in my air gapped environment.

Helm seems to have a new option "skip-schema-validation" that overcomes that problem as described here:
https://github.com/fluxcd/flux2/issues/4992

Is it possible, that Zarf supports that flag?

Zarf v0.41.0 seems to have the required version of its dependency on Helm:
https://github.com/zarf-dev/zarf/pull/3026

Use this zarf.yaml and create a package, try to deploy it in an air gapped cluster. You must also call "zarf package create --confirm" on the air gapped cluster. 
If you use that command in an environment, where it has internet access, it will work. But that's not our intended use case.

```
kind: ZarfPackageConfig

metadata:
  name: dagster
  description: auto-generated using `zarf dev generate`
  version: 1.8.7

components:
  - name: dagster
    required: true
    charts:
      - name: dagster
        version: 1.8.7
        url: https://dagster-io.github.io/helm
        namespace: dagster
    images:
      - docker.io/bitnami/minideb:stretch
      - docker.io/busybox:1.28
      - docker.io/dagster/dagster-celery-k8s:1.8.7
      - docker.io/dagster/user-code-example:1.8.7
      - docker.io/library/postgres:14.6
      - library/postgres:14.6

    actions:
      onDeploy:
        after:
          - cmd: |
            zarf tools kubectl label service dagster-dagster-webserver -n dagster zarf.dev/connect-name=dagster
          - cmd: |
            zarf tools kubectl annotate service dagster-dagster-webserver -n dagster zarf.dev/connect-description="Connect to the Dagster User Interface"
```

Thanks and greetings,
Josef

P.S.: I'm using Zarf v0.40.1
