### ISSUE TITLE
Zarf-agent does not maintain mutate after it already has `zarf-agent: patched` label applied 

### ISSUE THREAD

**Issue by a1994sc** [zarf-dev/zarf#3146]
### Environment
Device and OS: RHEL 9.4
App version: `v0.42.0
Kubernetes distro being used: RKE2, 1.31.1+rke2r2

### Steps to reproduce
1. Install fluxcd
1. Create gitrepo with the blow manifests
1. Wait for flux to re-apply the kustomization

### Expected result

The  `.spec.url` to point to the zarf docker registry

### Actual Result

The `.spec.url` reverts back to the url to `oci://registry1.dso.mil/bigbang`

### Comments

> We do not have a builtin template for the registry IP, but I'd like to solve this without one.
> Looks like the issue is that the Zarf agent checks for the `zarf-agent: patched` which is added during the initial mutation, and exits if it already exists. see [this block](https://github.com/zarf-dev/zarf/blob/df9c2120fbcd2d3c148c9bd095ae1faf55196501/src/internal/agent/hooks/flux-helmrepo.go#L50).
> I believe the mutation of every resource in the mutating webhook is idempotent, so we can just delete that check.

- Austin Abro, on Slack

### Manifests
`kustomization.yml`
```yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bigbang
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./.
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

`bigbang.yml`
```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: registry1
  namespace: flux-system
spec:
  interval: 2m
  type: oci
  url: oci://registry1.dso.mil/bigbang
```
