### ISSUE TITLE
 Allow `zarf` to create `private-registry` secret when a namespace is created

### ISSUE THREAD

**Issue by a1994sc** [zarf-dev/zarf#3365]
### Is your feature request related to a problem? Please describe.
When creating a namespace, or when a label is added to a namespace, that the `private-registry` secret is populated and managed by `zarf`

### Describe the behavior you'd like
- **When** a `namespace` resource is created
- **Then** after the namespace is created `zarf` creates the secret `private-registry`

### Additional context
- In the file [`src/internal/packager/helm/post-render.go`](https://github.com/zarf-dev/zarf/blob/90b764bbe0fa4fdf2ace164ca10c2a899e1013a7/src/internal/packager/helm/post-render.go#L162-L166) you already have logic to create the secret on existing namespaces
- Istio creates a configmap, `istio-ca-root-cert`, whenever a new namespace is created
  - The mutating webhook used by zarf could just always create the secret in all namespaces created after zarf is installed.

**Comment by brandtkeller** [comment]
I like the intent of this workflow. I do think it is worth noting that this would be net-new generation logic for the agent whose primary purpose is solely mutation to-date. Less of a controller behavior and more of an operator. 

The CLI could certainly take more of a stance in namespace adoption to fill some of the gap - But it would still rely on subsequent executions in order to reach desired state.

**Comment by a1994sc** [comment]
I mean, I think that `zarf` tends to flirt with being an operator with how it deploys things and how it operates inside the cluster with the webhook. Again personal opinion.

So do you think that a high level, do you think that there some be some for control loop that scans the namespaces and detects if thay secret is present and if not creates the secret?

**Comment by brandtkeller** [comment]
Agreed - I'd like to see more of a definitive and documented stance for Zarf on what is controlled and how. This would be a great discussion point for the community. 

Nonetheless wanted to drop some notes so that someone else doesn't think this is a mutation operation and rather see's the scope involved for this control loop.

**Comment by al-jeyapal** [comment]
For anyone who needs something in the interim, you can use ESO to sync secrets between the `zarf` namespace and newly created ones.

Define a zarf package which:

* Uses a component to deploy ESO.
* Uses a component to deploy manifest for the secret.

Simple manifest:

```
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: k8s-store
spec:
  provider:
    kubernetes:
      # Only allow store to pull from `zarf` namespace.
      remoteNamespace: zarf
      server:
        url: https://kubernetes.default
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: zarf
      auth:
        serviceAccount:
          # The service account automatically created by zarf has the correct permissions.
          name: zarf
          namespace: zarf

---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: private-registry
spec:
  # The name to be used on the ExternalSecrets.
  externalSecretName: private-registry-es
  namespaceSelectors:
  - matchExpressions:
    # Ignore namespaces managed by zarf as they already have the secret.
    - key: app.kubernetes.io/managed-by
      operator: NotIn
      values:
        - zarf
    # Ignore namespaces have the `zarf.dev/agent` explicity set, as these do not use the zarf registry.
    - key: zarf.dev/agent
      operator: DoesNotExist
  # Cluster External Secret refresh Time.
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: k8s-store
      kind: ClusterSecretStore
    # External Secret Refresh Time.
    refreshInterval: 10m
    target:
      name: private-registry
      creationPolicy: Owner
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: "{{ .dockerconfig | toString }}"
    data:
    - secretKey: dockerconfig
      remoteRef:
        key: private-registry
        property: .dockerconfigjson

---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: private-git-server
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: private-git-server-es
  namespaceSelectors:
  - matchExpressions:
    - key: app.kubernetes.io/managed-by
      operator: NotIn
      values:
        - zarf
    - key: zarf.dev/agent
      operator: DoesNotExist
  # Cluster External Secret refresh Time.
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: k8s-store
      kind: ClusterSecretStore
    # External Secret Refresh Time.
    refreshInterval: 10m
    target:
      name: private-git-server
      creationPolicy: Owner
    dataFrom:
      - extract:
          key: private-git-server
```
