### ISSUE TITLE
Zarf appears to not support non-standard ports for local image repositories

### ISSUE THREAD

**Issue by davidnraines** [zarf-dev/zarf#343]
### Environment
Device and OS:  RHEL 8.4
App version: 0.14.0
Kubernetes distro being used: k3s
Other:

### Summary

We are trying to use Zarf to deploy a mission application who's image is hosted on an image repository run by our corporate IT team.  That image repository uses a nonstandard port (4567).  Our Zarf package is failing to deploy, and it appears that the issue is that Zarf is not able to lookup the name of the target aliased image repository.

We are able to reproduce this issue by making a 1 line change to the "Doom" example under examples/game.

We are currently using Zarf v0.14

### Steps to reproduce

Under Zarf v0.14, we have modified the example/games demo to pull an image from an image repository with a non-standard port.  When we use this, Zarf appears to be unable to deploy.

We can execute the "zarf package create" step normally, but the process fails when we run "zarf package deploy".

```
kind: ZarfPackageConfig
metadata:
  name: appliance-demo-doom
  description: "Demo Zarf appliance mode with doom game"

components:
  - name: baseline
    required: true
    manifests: manifests

    images:
      - gitlab.progeny.net:4567/nosis_paas/zarf-test/sample-sso-webapp:1.0
```

The above code is a modified version of the examples/game demo.  I have attached the full source code here:

[game.zip](https://github.com/defenseunicorns/zarf/files/8118492/game.zip)

We have _attempted_ to fix this issue by adding this image registry to the "registries.yaml" file under assets/misc/registries.yaml, and rebuilding / redeploying the zarf-init package, but that does not appear to have fixed the issue.  The modified file is here: 

```
mirrors:
  registry.dso.mil:
    endpoint:
      - "https://###ZARF_TARGET_ENDPOINT###"
  registry1.dso.mil:
    endpoint:
      - "https://###ZARF_TARGET_ENDPOINT###"
  docker.io:
    endpoint:
      - "https://###ZARF_TARGET_ENDPOINT###"
  registry-1.docker.io:
    endpoint:
      - "https://###ZARF_TARGET_ENDPOINT###"
  ghcr.io:
    endpoint:
      - "https://###ZARF_TARGET_ENDPOINT###"
  registry.opensource.zalan.do:
    endpoint:
      - "https://###ZARF_TARGET_ENDPOINT###"
  "gitlab.progeny.net:4567":
    endpoint:
      - "https://###ZARF_TARGET_ENDPOINT###"
```

### Expected result
The image loaded in the Zarf "tar.zst" file is successfully loaded into the local image repository.

### Actual Result
The image loaded in the Zarf "tar.zst" file is not loaded into the image repository
### Visual Proof (screenshots, videos, text, etc)
![Zarf-deploy-error](https://user-images.githubusercontent.com/2481096/155177542-abcf2eb1-83f3-4e9f-8f83-55aa3a091001.png)

### Severity/Priority
Blocks our ability to use Zarf
