### ISSUE TITLE
Zarf errors when absolute file paths are used in components.files.source

### ISSUE THREAD

**Issue by AustinAbro321** [zarf-dev/zarf#3475]
### Environment
App version: v0.47.0-v0.48.1
### Steps to reproduce
1.  a zarf.yaml with a component with an absolute path
```
components:
  - name: baseline
    files:
      - source: /home/austin/code/zarf/cosign.pub
        target: here.pub
```
2. build package with zarf package create
### Expected result

The package builds successfully

### Actual Result

```go
2025-02-06 14:22:07 ERR failed to create package: unable to copy file /home/austin/code/secondZarf/cosign.pub: lstat home/austin/code/secondZarf/cosign.pub: no such file or directory
```

### Severity/Priority

Medium, it seems this was already broken with imports, but allowed in the base package. It's simple enough to fix
