### ISSUE TITLE
Option to anonymize metadata in built Zarf Package

### ISSUE THREAD

**Issue by sei-pearl** [zarf-dev/zarf#3570]
### Is your feature request related to a problem? Please describe.
When using Zarf the other day I noticed that there is metadata about which user and hostname built a package. That part is fine, but there are situations where that data cannot exist in an environment. I'm proposing a new cli flag for package creation to leave that metadata blank or allow for configuration of different values. 

### Describe the behavior you'd like

- The user is ready to build the package.
- `zarf package create --anonymize <other flags> .`
- The resulting `zarf.yaml` contained in the package has metadata removed. 

I'd be willing to create a PR for this, but would like feedback/thoughts on how the functionality should be implemented.

**Comment by ktarplee** [comment]
I want to second this idea and pile on.

```yaml
build:
  terminal: your-machines-hostname
  user: your-username
  architecture: amd64 # target architecture
  timestamp: Sun, 20 Apr 2025 05:42:45 -0700 # build timestamp
  version: v0.52.1
  migrations:
  - scripts-to-actions
  - pluralize-set-variable
  lastNonBreakingVersion: v0.27.0
```

It seems to me to be a minor security issue to have the hostname and username in this block that is ultimately published in a zarf package.  I also think the timezone in the timestamp is a leak of information as well.  I think that should be converted to the RFC3339 format or even better removed from the metadata all together so we can have a `zarf package create .` that makes reproducible zarf package archives.  See my comment [here](https://github.com/zarf-dev/zarf/issues/3702#issuecomment-2817159157)

The target architecture is probably fine but it might be an issue if it was the architecture of the machine that was building the package.
