### ISSUE TITLE
Add command to zarf to format zarf.yaml

### ISSUE THREAD

**Issue by zachariahmiller** [zarf-dev/zarf#3576]
### Is your feature request related to a problem? Please describe.
It would be really nice to be able to run a command like `zarf fmt` or `zarf dev fmt` that would properly format a zarf.yaml and/or zarf.yamls recursively in a directory, including some opinionation and new lines for readability, not all condensed like we see in the console view of a zarf.yaml.  

A good example of this is the `terraform fmt` or `terraform fmt -recursive` commands.

### Describe the behavior you'd like

- **Given** zarf.yaml file exists
- **When**i run `zarf fmt .`
- **Then** zarf.yaml gets formatted in a consistent, readable way. 

### Describe alternatives you've considered
using other tools, but some yaml parsers actually break the zarf.yaml schema and others dont preserve newlines making it very hard to read.

### Additional context
This is coming to a head as part of the need internally to bulk update 100s of packages and that there has not been a good, repeatable way to do this that doesnt cause other issues. I think ideally this would also be exposed as part of the sdk. 

I would personally love to never debate the formatting of a zarf.yaml again and defer to the tool.

Examples:

```yaml
kind: ZarfPackageConfig
metadata:
  name: valkey
  description: "A deployment of Valkey (a Redis alternative by the Linux Foundation)"
  url: https://github.com/valkey-io/valkey
  version: "8.0.1-uds.1"

variables:
  - name: DOMAIN
    default: "waynes.world"

components:
  - name: valkey
    required: true
    only:
      flavor: upstream
    import:
      path: common
    charts:
      - name: valkey
        valuesFiles:
          - ./values/upstream-values.yaml
    images:
      - bitnami/valkey:8.0.1-debian-12-r2
      - docker.io/bitnami/redis-exporter:1.65.0-debian-12-r2
      - docker.io/bitnami/valkey-sentinel:8.0.1-debian-12-r1

  - name: valkey
    required: true
    only:
      flavor: unicorn
    import:
      path: common
    charts:
      - name: valkey
        valuesFiles:
          - ./values/unicorn-values.yaml
    images:
      - cgr.dev/du-uds-defenseunicorns/valkey:8.0.1
      - cgr.dev/du-uds-defenseunicorns/prometheus-redis-exporter-bitnami:1.65.0
      - docker.io/bitnami/valkey-sentinel:8.0.1-debian-12-r1
```

or

```yaml
kind: ZarfPackageConfig
metadata:
  name: gitlab-common
  description: "UDS GitLab Common Package"

components:
  - name: gitlab
    required: true
    charts:
      - name: uds-gitlab-config
        namespace: gitlab
        version: 0.2.0
        localPath: ../charts/config
      - name: gitlab
        namespace: gitlab
        url: https://charts.gitlab.io/
        gitPath: chart
        version: "8.9.1"
        valuesFiles:
          - ../values/common-values.yaml
      - name: uds-gitlab-settings
        namespace: gitlab
        version: 0.1.0
        localPath: ../charts/settings
    actions:
      onDeploy:
        before:
          - cmd: |
              if [ "$ZARF_VAR_GENERATE_STORAGE_SECRET" = "true" ]; then
                ./zarf tools kubectl annotate secret -n gitlab gitlab-object-store meta.helm.sh/release-namespace=gitlab --overwrite || true
                ./zarf tools kubectl label secret -n gitlab gitlab-object-store app.kubernetes.io/managed-by=Helm --overwrite || true
                ./zarf tools kubectl annotate secret -n gitlab gitlab-object-store meta.helm.sh/release-name=uds-gitlab-config --overwrite || true
              fi
        after:
          - description: Validate GitLab Package
            maxTotalSeconds: 300
            wait:
              cluster:
                kind: packages.uds.dev
                name: gitlab
                namespace: gitlab
                condition: "'{.status.phase}'=Ready"
```
