### ISSUE TITLE
Make injector repo and gitea chart path configurable

### ISSUE THREAD

**Issue by chiqomar** [zarf-dev/zarf#3722]
### Is your feature request related to a problem? Please describe.
We are currently composing and creating a version of our own zarf init, but references for artifacts, images, and charts have to be proxied. There is a way to do this registries using `--registry-override`, and for the gitea image using `--set AGENT_IMAGE_DOMAIN`, but there are two conspicuous ones where it is not configurable:
- In `packages/zarf-registry/zarf.yaml`, the location of the injector binary is `zarf-init-resources.s3.us-east-1.amazonaws.com`; if this was a variable with a default, it would make things a little easier
- In `packages/gitea/zarf.yaml`, `dl.gitea.io` is not overrideable, at least not easily.

### Describe the behavior you'd like

Both of these values should be set as variables in their respective zarf.yaml files, and set to defaults with the current values. They should thus be overrideable using a `--set` flag on `zarf package create`

### Describe alternatives you've considered
I am currently using a sed command to do this instead:
```bash
        sed -i-bk 's|zarf-init-resources\.s3\.us-east-1\.amazonaws.com|our-proxied-path.com|' packages/zarf-registry/zarf.yaml
        sed -i-bk 's|dl\.gitea\.io|our-proxied-path.com|' packages/gitea/zarf.yaml
        zarf package create . --confirm ...
```

**Comment by brandtkeller** [comment]
Thanks for the issue. I don't believe the requests here are unreasonable given efforts to make Init components more configurable. We welcome PR's otherwise we will get this on our backlog.

**Comment by brandtkeller** [comment]
#4070 updated what is exposed for the injector (please validate these changes do or do-not work for your use-case). 

The gitea configurations proposed are still applicable.

**Comment by AustinAbro321** [comment]
Instead of accomplishing this through my templates, I would recommend that you do this though a skeleton package such as similar to what is done in https://github.com/defenseunicorns/delivery-zarf-init. 

The injector component only has a single file. To use your own injector source you could do something like this:
```yaml
  - name: zarf-injector
    required: true
    files:
      # Rust Injector Binary
      - source: https://<my-repo-or-repository>/releases/download/v0.3.0/zarf-injector-amd64 #Instead of 
        target: "###ZARF_TEMP###/zarf-injector"
        shasum: "54c37ca19a101c795786510cb89cf4fe2aa7504d4c399985606a3d8f58f42119"
        executable: true
```

And to use your own URL for the gitea chart you could do something like this:
```yaml
  - name: git-server
    import:
      url: oci://ghcr.io/zarf-dev/packages/init:v0.73.0
    charts:
      - name: gitea
        url: oci://<my-chart-registry>/giteacharts/gitea
```
