### ISSUE TITLE
Zarf fails to install seed registry on an unschedulable node with custom init package

### ISSUE THREAD

**Issue by garzdin-stackit** [zarf-dev/zarf#3741]
### Environment
Device and OS: MacOS Sonoma 14.7.4 (23H420)
App version: v0.53.0
Kubernetes distro being used: vanilla v1.32.0
Other: -

### Steps to reproduce
1. Create a custom composed zarf-init package
2. Specify custom Helm chart values for the seed registry:
```yaml
- name: zarf-seed-registry
    required: true
    import:
      path: zarf/packages/zarf-registry
    charts:
      - name: docker-registry
        valuesFiles:
          - registry-values.yaml
```
3. Add tolerations for the seed registry in the `registry-values.yaml`
```yaml
tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/not-ready
    operator: Exists
```

### Expected result
I expect for the seed registry to install

### Actual Result
The installation of the seed registry is blocked, because the tolerations are not taken into account

### Severity/Priority
High

### Additional Context
This happens, because there's a hard-coded check for taints on nodes: https://github.com/zarf-dev/zarf/blob/v0.53.0/src/pkg/cluster/injector.go#L274

I'm running a single-node cluster and would like to install the CNI with Zarf, but I'm currently not able to because the node taint won't be removed until there's a CNI installed.
