### ISSUE TITLE
Pull issues when multiple images use the same cred helper

### ISSUE THREAD

**Issue by mjnagel** [zarf-dev/zarf#3761]
### Environment
Device and OS: MBP, macOS
App version: 0.54.0
Kubernetes distro being used: Irrelevant
Other:

### Steps to reproduce

This issue will require usage of a docker credential helper, however I believe it is reproducible without any paid image access.
1. Setup Chainctl following this guide: https://edu.chainguard.dev/chainguard/chainctl-usage/how-to-install-chainctl/
2. Make sure you setup the docker cred helper: https://edu.chainguard.dev/chainguard/chainctl-usage/how-to-install-chainctl/#configure-a-docker-credential-helper
3. Run `chainctl auth logout` to make sure you are not logged in.
4. `zarf package create` the below package:

```yaml
kind: ZarfPackageConfig
metadata:
  name: docker-cred-test

components:
  - name: test
    required: true
    images:
      - cgr.dev/chainguard/bash:latest
      - cgr.dev/chainguard/busybox:latest
      - cgr.dev/chainguard/crane:latest
      - cgr.dev/chainguard/curl:latest
```

### Expected result

Zarf/chainctl opens a single auth window, zarf pulls images successfully.

### Actual Result

Zarf/chainctl open an auth window per-image, none of the auth windows succeed and the package creation fails.

### Severity/Priority

Low/Medium - very poor UX when using a cred helper, but if you are able to get past initial auth you can create the package the second time.

### Additional Context

If you comment out images above you should see it open 1, 2, 3, or 4 auth windows (based on the number of images).

I originally experienced this with paid images, but was able to reproduce with the package above. Hopefully this can be replicated without any Chainguard paid access.
