### ISSUE TITLE
Import does not identify source as a URL if templated

### ISSUE THREAD

**Issue by brandtkeller** [zarf-dev/zarf#3762]
### Steps to reproduce
1. template a file source 
```yaml
- source: https://###ZARF_PKG_TMPL_INJECTOR_DOMAIN###/injector/###ZARF_PKG_TMPL_INJECTOR_VERSION###/zarf-injector-arm64
        target: "###ZARF_TEMP###/zarf-injector"
        shasum: "###ZARF_PKG_TMPL_INJECTOR_AMD64_SHASUM###"
```
2. Execute a `zarf dev inspect definition <path to zarf.yaml>`

### Actual Result
```yaml
files:
  - source: packages/zarf-registry/https:/zarf-init-resources.s3.us-east-1.amazonaws.com/injector/2025-03-24/zarf-injector-arm64
    shasum: <redacted>
    target: "###ZARF_TEMP###/zarf-injector"
    executable: true
```

### Additional Context
The above example is attempted in #3752 and fails as 
> templating happens after imports, Zarf doesn't see the file as a URL during imports and therefore adds the path to the imported component

https://github.com/zarf-dev/zarf/pull/3752#discussion_r2069203027
