### ISSUE TITLE
Add package flavor to zarf internal values

### ISSUE THREAD

**Issue by sgettys** [zarf-dev/zarf#3769]
### Is your feature request related to a problem? Please describe.
I am developing a package that I want to change behaviors of a required "flavorless" component based on the flavor that the package was built for. Zarf could expose as part of its internal values what the package flavor is when deploying.

### Describe the behavior you'd like

- **Given** a zarf package built against a flavor
- **When** the package is deployed
- **Then** an internal zarf value (ZARF_PKG_FLAVOR) is available that will report the flavor of the package

**Comment by rdmcneil** [comment]
I think I am looking for something similar. 
Zarf currently supports flavor selection only via components[].only.flavor, which gates entire components at package creation time. When only a small part of a component differs between flavors (e.g., an additional Helm values file), users must duplicate the entire component definition, leading to bloated and harder-to-maintain zarf.yaml files.

```
zarf-current-flavor-use.yaml
components:
  - name: gitlab-base
    description: Baseline GitLab install
    only:
        flavors: baseFlavor
    charts:
      - name: gitlab
        namespace: gitlab
        releaseName: gitlab
        valuesFiles:
          - values/gitlab-base.yaml
    images:
      - bitnami/analytics/redis-exporter:v1.79.0
      - bitnami/redis:8.2.2
      - gitlab/gitlab/certificates:18.5.1
      - gitlab/gitlab/cfssl-self-sign:1.6.1
      - gitlab/gitlab/gitaly:18.5.1
      - gitlab/gitlab/gitlab-base:18.5.1
      - gitlab/gitlab/gitlab-container-registry:18.5.1
      - gitlab/gitlab/gitlab-shell:18.5.1
      - gitlab/gitlab/gitlab-sidekiq:18.5.1
      - gitlab/gitlab/gitlab-toolbox:18.5.1
      - gitlab/gitlab/gitlab-webservice:18.5.1
      - gitlab/gitlab-workhorse:18.5.1
      - gitlab/gitlab/kubectl:18.5.1
      - minio/mc:RELEASE.2024-10-02T08-27-28Z
      - minio/minio:RELEASE.2024-06-04T19-20-08Z
      - gitlab/gitlab/gitlab-exporter:18.5.1
      - redhat/ubi/ubi9:9.6
  - name: gitlab-external-redis
    description: Baseline GitLab install
    only:
        flavors: externalRedis
    charts:
      - name: gitlab
        namespace: gitlab
        releaseName: gitlab
        only:
           flavors: baseFlavor
        valuesFiles:
          - values/gitlab-base.yaml
        only:
           flavors: externalRedis
        valuesFiles:
          - values/gitlab-base.yaml
          - values/gitlab-external-redis-values.yaml
    images:
      - gitlab/gitlab/certificates:18.5.1
      - gitlab/gitlab/cfssl-self-sign:1.6.1
      - gitlab/gitlab/gitaly:18.5.1
      - gitlab/gitlab/gitlab-base:18.5.1
      - gitlab/gitlab/gitlab-container-registry:18.5.1
      - gitlab/gitlab/gitlab-shell:18.5.1
      - gitlab/gitlab/gitlab-sidekiq:18.5.1
      - gitlab/gitlab/gitlab-toolbox:18.5.1
      - gitlab/gitlab/gitlab-webservice:18.5.1
      - gitlab/gitlab-workhorse:18.5.1
      - gitlab/gitlab/kubectl:18.5.1
      - minio/mc:RELEASE.2024-10-02T08-27-28Z
      - minio/minio:RELEASE.2024-06-04T19-20-08Z
      - gitlab/gitlab/gitlab-exporter:18.5.1
      - redhat/ubi/ubi9:9.6
```
The above is rather bulky and repetitive. To consolidate reused components the sub-objects could be managed with a similar flavor as seen elsewhere.  The example below lays out the general idea. It would reduce repeated code and confusion with replicated components.  

```
zarf-with-internal-value-flavors.yaml
components:
  - name: gitlab-base
    description: GitLab install
    charts:
      - name: gitlab
        namespace: gitlab
        releaseName: gitlab
        only:
           flavors: baseFlavor
           valuesFiles:
             - values/gitlab-base.yaml
        only:
             flavors: externalRedis
             valuesFiles:
              - values/gitlab-base.yaml
              - values/gitlab-external-redis-values.yaml
    images:
      - gitlab/gitlab/certificates:18.5.1
      - gitlab/gitlab/cfssl-self-sign:1.6.1
      - gitlab/gitlab/gitaly:18.5.1
      - gitlab/gitlab/gitlab-base:18.5.1
      - gitlab/gitlab/gitlab-container-registry:18.5.1
      - gitlab/gitlab/gitlab-shell:18.5.1
      - gitlab/gitlab/gitlab-sidekiq:18.5.1
      - gitlab/gitlab/gitlab-toolbox:18.5.1
      - gitlab/gitlab/gitlab-webservice:18.5.1
      - gitlab/gitlab-workhorse:18.5.1
      - gitlab/gitlab/kubectl:18.5.1
      - minio/mc:RELEASE.2024-10-02T08-27-28Z
      - minio/minio:RELEASE.2024-06-04T19-20-08Z
      - gitlab/gitlab/gitlab-exporter:18.5.1
      - redhat/ubi/ubi9:9.6
    images:
       only:
          flavors: baseFlavor
        - bitnami/analytics/redis-exporter:v1.79.0
        - bitnami/redis:8.2.2
```
