### ISSUE TITLE
When specifying a helm chart via a localPath, the version field should not be required

### ISSUE THREAD

**Issue by ktarplee** [zarf-dev/zarf#3813]
Right now components that use helm charts from a localPath are required to specify the version as well.  This is redundant since the chart obviously has a chart version in the Chart.yaml file.  What is worse is that the version specified below can be different than the chart which is at best misleading.

```yaml
- name: splash
   localPath: ../charts/splash
   version: "0.0.1" # THIS SHOULD NOT BE REQUIRED WHEN localPath IS SPECIFIED
   namespace: default
   valuesFiles:
      - splash-values.yaml
```
