### ISSUE TITLE
Allow for optional authentication tokens to avoid unauthenticated rate limits

### ISSUE THREAD

**Issue by chance-coleman** [zarf-dev/zarf#3816]
### Is your feature request related to a problem? Please describe.

I'm running into rate limiting issues when Zarf attempts to pull raw resources from GitHub (e.g., Kubernetes CRDs) during a deployment. GitHub recently introduced stricter rate limits for unauthenticated requests to `raw.githubusercontent.com`, which results in errors like:

```
failed to download https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.3.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml: bad HTTP status: 429 Too Many Requests
```

This prevents CI/CD pipelines from reliably pulling raw files as part of Zarf package deploys.

Relevant links:

* [https://github.com/orgs/community/discussions/159123#discussioncomment-13148279](https://github.com/orgs/community/discussions/159123#discussioncomment-13148279)
* [https://github.blog/changelog/2025-05-08-updated-rate-limits-for-unauthenticated-requests/](https://github.blog/changelog/2025-05-08-updated-rate-limits-for-unauthenticated-requests/)

---

### Describe the behavior you'd like

* **Given** a deployment that includes GitHub-hosted raw file references (e.g., CRDs in a Zarf package init container or script)
* **When** Zarf executes downloads from `raw.githubusercontent.com`
* **Then** Zarf should allow users to optionally supply an authentication token (e.g., GitHub PAT) to avoid rate limits

We are currently using the following manifest structure:

```yaml
- name: gateway-api-crds
  required: true
  manifests:
    - name: gateway-api-crds
      files:
        - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.3.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
        - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.3.0/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
        - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.3.0/config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
        - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.3.0/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
```

We'd like to propose adding an optional field in the manifest or in the CLI that lets users supply an authentication token, such as:

```yaml
auth:
  githubToken: "${ZARF_GITHUB_TOKEN}"
```

Or have Zarf automatically use an environment variable like `ZARF_GITHUB_TOKEN` if present.

---

### Describe alternatives you've considered

* Adding retry logic with exponential backoff, though this doesn’t guarantee success if the limit is exceeded.
* Continuing to use unauthenticated requests and deal with the pain of failed pulls.

---

### Additional context

I tested authenticated requests manually using a GitHub PAT with this command and it successfully bypassed the rate limiting:

```bash
curl -H "Authorization: token $GITHUB_TOKEN" \
     -v https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.3.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
```

This demonstrates that authentication resolves the issue. A Zarf-native solution for authenticated fetches would make package deployments more robust and CI-friendly.
