### ISSUE TITLE
Enhancing CVE Identification & Reporting Process

### ISSUE THREAD

**Issue by brandtkeller** [zarf-dev/zarf#3842]
## Background

Currently, our CVE triage relies on dependabot scans and manual reviews. This approach can lead to delays in vulnerability awareness, inconsistent reporting formats, and gaps in downstream processes (e.g., generating VEX data). To elevate our security posture and streamline vulnerability management, I propose an automated, nightly SBOM-based scanning & reporting pipeline on `main`.

---

## Proposed Workflow

1. **Nightly SBOM Generation & Scanning**

   * Use syft to generate an SPDX SBOM for the `main` branch every night.
   * Feed the resulting SBOM into grype, which produces:

     * **SARIF** output (for GitHub’s Code Scanning UI)
     * A machine-readable JSON report of discovered CVEs

2. **Locally Reproducible**

   * Ensure all steps can be reproduced locally - aiding in the review and mitigation process. 
   * This should likely use a new / existing `make` target(s)

3. **Artifact Upload**

   * Upload both the SBOM and the rendered CVE report as workflow artifacts for audit and offline review by any consumer without tooling available.

4. **High-Severity Alerting**

   * If any CVE with **severity ≥ High** is detected, fail the job (or optionally just raise a warning) and trigger a GitHub issue (via \[actions/create-issue]) tagging `@zarf-maintainers` (and maybe optionally a future`@security-team`).

---

## Example GitHub Actions Snippet

```yaml
# .github/workflows/cve-report.yml
name: "Nightly SBOM & CVE Report"

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 02:00 UTC
  workflow_dispatch:

jobs:
  sbom-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh \
            | sh -s -- -b /usr/local/bin

      - name: Generate SBOM with Syft
        id: sbom
        run: |
         make sbom

      - name: Scan SBOM with Grype
        id: scan
        run: |
          make sbom-scan

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif-file }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SBOM-and-CVE-report
          path: |
            ${{ steps.sbom.outputs.sbom-file }}
            CVE-Report.md

      - name: Fail on High/Critical CVEs
        if: >
          contains(fromJson(steps.scan.outputs.json-file).matches.*.severity, 'High') ||
          contains(fromJson(steps.scan.outputs.json-file).matches.*.severity, 'Critical')
        run: |
          echo "High or Critical CVE detected; creating issue."
          gh issue create \
            --title "🚨 High-Severity CVE(s) Detected on main" \
            --body-file CVE-Report.md \
            --label "security" \
            --assignee @zarf-maintainers

```

---
5. **Documentation Updates**

  * Update documentation to provide consumers with the most accurate steps to stay up-to-date with vulnerabilities on their current version of zarf. 
  * Indicate how they can obtain an sbom for their released version of zarf (both release artifacts) 
---

## Integration with `.grype.yaml` & VEX Support

* Our existing `.grype.yaml` already includes support for VEX
* By driving scans through this centralized config, we maintain:

  * **Consistency** across local dev, CI, and ad-hoc CLI scans
  * **Provenance** for any suppressed CVEs (VEX data is centrally managed and documented)

---

## Next Steps

1. Review and merge the workflow YAML
2. Update project README with “Security & SBOM” section linking to the new report.
3. Configure retention policies for artifacts (e.g., 30 days).
4. Monitor initial results for false positives/negatives and tune `.grype.yaml` as needed.
