### ISSUE TITLE
Package creation to non-existent output folder fails in 0.55.x

### ISSUE THREAD

**Issue by mjnagel** [zarf-dev/zarf#3860]
### Environment
Device and OS: MBP, macOS
App version: 0.55.x (0.55.2 and 0.55.5)
Kubernetes distro being used: N/A
Other:

### Steps to reproduce
1. Create a zarf config file with a defined output directory:
```yaml
package:
  create:
    output: build
```
2. Attempt to create a basic zarf package such as the below (`zarf p create --confirm`):
```yaml
kind: ZarfPackageConfig
metadata:
  name: test

components:
  - name: test
    required: true
    images:
      - busybox
```

### Expected result

Package creates, automatically creating the `build` directory.

### Actual Result

`build` directory is not created, package creation fails with this error:
```
2025-05-27 08:41:06 ERR failed to create package: unable to create package: failed to create build/zarf-package-test-arm64.tar.zst: open build/zarf-package-test-arm64.tar.zst: no such file or directory
```

### Severity/Priority

Low/Medium

### Additional Context

Marking this as a possible bug because this is a regression - in our packages we have been "relying" on this behavior for CI builds for a year+, if I revert to 0.54.0 the folder is autocreated for me.
