### ISSUE TITLE
Bottlerocket FIPS filesystem open error

### ISSUE THREAD

**Issue by jsmith1988** [zarf-dev/zarf#3861]
### Environment
Device and OS: `EKS` with `BOTTLEROCKET_x86_64_FIPS` images
App version: latest
Kubernetes distro being used: 1.31 or 1.32

### Steps to reproduce
1. Create EKS cluster with `BOTTLEROCKET_x86_64_FIPS` node group
2. Initialize Zarf
3. Deploy the following package
```
kind: ZarfPackageConfig
metadata:
  name: istio-platform
  description: Istio
  version: "0.1.0-dev"
  source: https://github.com/test
  vendor: test
components:
  - name: istio
    required: true
    charts:
      - name: istio-base
        version: "1.22.3"
        namespace: istio-system
        url: https://istio-release.storage.googleapis.com/charts
        repoName: base
      - name: istio-discovery
        version: "1.22.3"
        namespace: istio-system
        url: https://istio-release.storage.googleapis.com/charts
        repoName: istiod
    images:
      - docker.io/istio/pilot:1.22.3
      - index.docker.io/istio/pilot:sha256-6964e8fbca921fb1c5a3d27ea953a8eaa0ca0051a2c8fcdb8a96870027ef3153.sig
    actions:
      onRemove:
        after:
          - cmd: kubectl delete namespace istio-system
      onDeploy:
        after:
          - wait:
              cluster:
                kind: deployment
                name: istiod
                namespace: istio-system
                condition: available
  - name: istio-gateway
    required: true
    charts:
      - name: istio-ingressgateway
        version: "1.22.3"
        namespace: istio-system
        url: https://istio-release.storage.googleapis.com/charts
        repoName: gateway
    images:
      - docker.io/istio/pilot:1.22.3
      - docker.io/istio/proxyv2:1.22.3
    actions:
      onDeploy:
        before:
          - cmd: kubectl label namespace istio-system istio-injection=enabled --overwrite
        after:
          - wait:
              cluster:
                kind: deployment
                name: istio-ingressgateway
                namespace: istio-system
                condition: available
```

### Expected result
Istio zarf package can be deployed

### Actual Result
There is a permission denied when trying to access the file system
`filesystem: open /var/lib/registry/docker/registry/v2/repositories/istio/proxyv2/_manifests/tags/1.22.3-zarf-2656446571/current/link: permission denied`

### Visual Proof (screenshots, videos, text, etc)
```
time="2025-05-27T14:26:05.226233661Z" level=warning msg="error authorizing context: basic authentication challenge for realm \"Registry Realm\": invalid authorization credential" go.version=go1.23.7 http.request.host="127.0.0.1:31999" http.request.id=757896c9-60b8-4d10-a556-763972d02fd5 http.request.method=HEAD http.request.remoteaddr="192.168.173.226:38573" http.request.uri=/v2/istio/proxyv2/manifests/1.22.3-zarf-2656446571 http.request.useragent=containerd/1.7.27+bottlerocket instance.id=dff6988e-3342-4662-90c9-68fefbe21beb service=registry vars.name=istio/proxyv2 vars.reference=1.22.3-zarf-2656446571 version=3.0.0
192.168.173.226 - - [27/May/2025:14:26:05 +0000] "HEAD /v2/istio/proxyv2/manifests/1.22.3-zarf-2656446571 HTTP/1.1" 401 156 "" "containerd/1.7.27+bottlerocket"
time="2025-05-27T14:26:05.29013137Z" level=info msg="authorized request" auth.user.name=zarf-pull go.version=go1.23.7 http.request.host="127.0.0.1:31999" http.request.id=04ce7236-85c7-461f-92d7-cdf0d5783e64 http.request.method=HEAD http.request.remoteaddr="192.168.173.226:38573" http.request.uri=/v2/istio/proxyv2/manifests/1.22.3-zarf-2656446571 http.request.useragent=containerd/1.7.27+bottlerocket instance.id=dff6988e-3342-4662-90c9-68fefbe21beb service=registry vars.name=istio/proxyv2 vars.reference=1.22.3-zarf-2656446571 version=3.0.0
time="2025-05-27T14:26:05.29027131Z" level=error msg="response completed with error" auth.user.name=zarf-pull err.code=unknown err.detail="filesystem: open /var/lib/registry/docker/registry/v2/repositories/istio/proxyv2/_manifests/tags/1.22.3-zarf-2656446571/current/link: permission denied" err.message="unknown error" go.version=go1.23.7 http.request.host="127.0.0.1:31999" http.request.id=04ce7236-85c7-461f-92d7-cdf0d5783e64 http.request.method=HEAD http.request.remoteaddr="192.168.173.226:38573" http.request.uri=/v2/istio/proxyv2/manifests/1.22.3-zarf-2656446571 http.request.useragent=containerd/1.7.27+bottlerocket http.response.contenttype=application/json http.response.duration=63.481168ms http.response.status=500 http.response.written=221 instance.id=dff6988e-3342-4662-90c9-68fefbe21beb service=registry vars.name=istio/proxyv2 vars.reference=1.22.3-zarf-2656446571 version=3.0.0
192.168.173.226 - - [27/May/2025:14:26:05 +0000] "HEAD /v2/istio/proxyv2/manifests/1.22.3-zarf-2656446571 HTTP/1.1" 500 221 "" "containerd/1.7.27+bottlerocket"
```

Deployment
```
2025-05-27 10:22:42 INF pushing image name=docker.io/istio/pilot:1.22.3
2025-05-27 10:22:43 INF pushing image name=docker.io/istio/proxyv2:1.22.3
2025-05-27 10:23:15 INF pushing image name=docker.io/istio/proxyv2:1.22.3
2025-05-27 10:24:38 INF processing Helm chart name=istio-ingressgateway version=1.22.3 source=https://istio-release.storage.googleapis.com/charts
2025-05-27 10:24:38 INF performing Helm install chart=istio-ingressgateway
2025-05-27 10:39:39 INF performing Helm upgrade chart=istio-ingressgateway
2025-05-27 10:39:43 INF performing Helm upgrade chart=istio-ingressgateway
2025-05-27 10:39:46 ERR failed to deploy package: unable to deploy component "istio-gateway": unable to install chart after 3 attempts: All attempts fail:
#1: context deadline exceeded
#2: context deadline exceeded
#3: context deadline exceeded: if you need to remove the failed chart, use `zarf package remove`
```

### Severity/Priority
This could be a major blocker for us as we are targeting FIPS and this is one of the best images to use for it.

This appears to work fine on NON-FIPS bottle rocket image `BOTTLEROCKET_x86_64`
