### ISSUE TITLE
zarf dev find-images errors on absolute path for valuesFiles

### ISSUE THREAD

**Issue by alexifsp** [zarf-dev/zarf#3867]
### Environment
Device and OS: Linux
App version: 0.52.1
Kubernetes distro being used: K3s (doesn't matter)
Other:

### Steps to reproduce
1. Clone zarf repo:
2. cd to zarf/examples/helm-charts
3. in the zarf.yaml modify the path for values.yaml from: values.yaml
to

```yaml
charts:
      # Charts are organized in a list with unique chart names per component - note that a Zarf chart name does not need to match the chart name in a Chart.yaml
      - name: podinfo-local
        version: 6.4.0
        namespace: podinfo-from-local-chart
        # In this case `localPath` will load the podinfo chart that is located in the `chart` directory
        localPath: chart
        valuesFiles:
          - /home/coder/workspace/zarf/examples/helm-charts/values.yaml
        # Variables are used to override the default values in the chart
        # This can be overridden by the user at deployment time with the `--set` flag
        variables:
          - name: REPLICA_COUNT
            description: "Override the number of pod replicas"
            path: replicaCount
```
4. Execute zarf dev find-images with version 0.52.1 or above and observe the failure:

```bash
ERR unable to find images: unable to package the chart podinfo-local: unable to package the "podinfo-local" chart: unable to process the values for the package: unable to copy chart values file home/coder/workspace/zarf/examples/helm-charts/values.yaml: lstat home/coder/workspace/zarf/examples/helm-charts/values.yaml: no such file or directory
```

### Expected result
Until 0.51.0 this functionality worked as expected.
After refactor done in 0.52.1 this bug has been observed.

### Severity/Priority
High. Modifying current pipelines behavior.
