### ISSUE TITLE
Images with underscore in name not seen by zarf dev find-images

### ISSUE THREAD

**Issue by alexifsp** [zarf-dev/zarf#3868]
### Environment
Device and OS: Linux
App version: 0.51.0 - 0.55.5
Kubernetes distro being used: K3S (doesn't matter)
Other:

### Steps to reproduce
1. Create a chart with reference to an image that contains "_" in name:
Example: percona/mongoldb_exporter (the one where I found the issue)

### Expected result
When using container images with underscore in their names find-images should be able to discover them.

### Actual Result
Images with underscore in their names are not returned by zarf dev find-images command.

### Visual Proof (screenshots, videos, text, etc)
mongodb-exporter:

```yaml
components:
  - name: myproject
    images:
      - my.artifactory/dockerhub/percona/percona-server-mongodb-operator:1.19.1
      - my.artifactory/ghcr.io/ot-container-kit/redis-operator/redis-operator:v0.20.2
      # Possible images - myproject - myproject
      - my.artifactory/dockerhub/percona/percona-server-mongodb:5.0.29-25
      - my.artifactory/dockerhub/percona/percona-server-mongodb:6.0.21-18
      - my.artifactory/dockerhub/percona/percona-server-mongodb:7.0.18-11
      - my.artifactory/dockerhub/percona/percona-server-mongodb:8.0.8-3
      - my.artifactory/myproject-docker-dev/percona/mongodb-exporter:0.44.0
      - my.artifactory/quay.io/opstree/redis-exporter:v1.48.0
      - my.artifactory/quay.io/opstree/redis-sentinel:v6.2.17
      - my.artifactory/quay.io/opstree/redis-sentinel:v7.2.7
      - my.artifactory/quay.io/opstree/redis:v6.2.17
      - my.artifactory/quay.io/opstree/redis:v7.2.7
```
mongodb_exporter:

```yaml
components:
  - name: myproject
    images:
      - my.artifactory/dockerhub/percona/percona-server-mongodb-operator:1.19.1
      - my.artifactory/ghcr.io/ot-container-kit/redis-operator/redis-operator:v0.20.2
      # Possible images - myproject - myproject
      - my.artifactory/dockerhub/percona/percona-server-mongodb:5.0.29-25
      - my.artifactory/dockerhub/percona/percona-server-mongodb:6.0.21-18
      - my.artifactory/dockerhub/percona/percona-server-mongodb:7.0.18-11
      - my.artifactory/dockerhub/percona/percona-server-mongodb:8.0.8-3
      - my.artifactory/quay.io/opstree/redis-exporter:v1.48.0
      - my.artifactory/quay.io/opstree/redis-sentinel:v6.2.17
      - my.artifactory/quay.io/opstree/redis-sentinel:v7.2.7
      - my.artifactory/quay.io/opstree/redis:v6.2.17
      - my.artifactory/quay.io/opstree/redis:v7.2.7
```

### Additional Context
As a workaround I had to tag the official image to an image name with "-" but this will of course disrupt my automatic dependency update as I can't refer to official image.

**Comment by jasonwashburn** [comment]
@alexifsp / Zarf Team
I believe this issue may have been corrected in more recent releases. While creating a minimal reproduction I found that the current version of Zarf (v0.63.0) seems to find the image name referenced in the initial report as expected. 

I used the following to test it... (also available [here](https://github.com/jasonwashburn/zarf-find-image-underscore))

```yaml
# ./zarf.yaml
kind: ZarfPackageConfig
metadata:
  name: underscore-test
  description: Simple test of underscores in image names
  version: 0.0.1

components:
  - name: underscore-test
    manifests:
      - name: underscore-test
        namespace: underscore
        files:
          - manifests/deployment.yaml
    images:
      - my.artifactory/myproject-docker-dev/percona/mongodb_exporter:0.44.0
      - my.artifactory/myproject_docker-dev/percona/mongodb_exporter:0.44.0
```

```yaml
# ./manifests/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: underscore-test
spec:
  selector:
    matchLabels:
      app: underscore-test
  template:
    metadata:
      labels:
        app: underscore-test
    spec:
      containers:
        - name: simple-underscore-test
          image: my.artifactory/myproject-docker-dev/percona/mongodb_exporter:0.44.0
        - name: full-underscore-test
          image: my.artifactory/myproject_docker_dev/percona/mongodb_exporter:0.44.0
        - name: not-listed-separately-in-components-test
          image: only.in.chart/not-in-components-images/percona/mongodb_exporter:0.44.0
```
Output:

 ```text
❯ zarf dev find-images
2025-10-04 09:46:56 INF looking for images in component name=underscore-test resourcesCount=1
2025-10-04 09:46:56 INF looking up cosign artifacts for discovered images count=3

components:
  - name: underscore-test
    images:
      - my.artifactory/myproject-docker-dev/percona/mongodb_exporter:0.44.0
      - my.artifactory/myproject_docker_dev/percona/mongodb_exporter:0.44.0
      - only.in.chart/not-in-components-images/percona/mongodb_exporter:0.44.0
```

**Comment by alita1991** [comment]
Hi @jasonwashburn / Zarf Team

I actually needed this fix, and I can confirm that it doesn’t work when the images are defined in the config map. Here’s an example:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-manifest
data:
  manifest: |
    defaultChannel: "8.x"
    supportedChannels:
      7.x:
        version: "7.0.18-11"
        upgradesTo:
        - 7.x
        - 8.x
      8.x:
        version: "8.0.8-3"
        upgradesTo: []
  exporter-image-7.0.18-11: my.artifactory/myproject-docker-dev/mongodb-exporter:0.47.1
  exporter-image-8.0.8-3: my.artifactory/myproject_docker_dev/mongodb_exporter:0.47.1
```

The image that contains "-" is always identified, while the image that contains "_" is not found.
