### ISSUE TITLE
Certain annotation data breaks `zarf package publish` for certain registries

### ISSUE THREAD

**Issue by willswire** [zarf-dev/zarf#3876]
### Environment
Device and OS: MacBook Pro, macOS 15.5 (24F74)
App version: v0.55.5
Kubernetes distro being used: N/A
Other: GitLab Container Registry [v17.11.2-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v17.11.2-ee)

### Steps to reproduce
1. Create a Zarf package with an annotation containing a base64-encoded SVG
2. Publish the Zarf package to a GitLab container registry

### Expected result
The artifact pushes successfully and is stored in the registry

### Actual Result
The artifact fails to push, and is partially stored in the registry

### Visual Proof (screenshots, videos, text, etc)

```yaml
kind: ZarfPackageConfig
metadata:
  name: external-secrets
  description: "UDS External Secrets package"
  version: "dev"
  annotations:
    dev.uds.title: External Secrets
    dev.uds.tagline: Integrate external secret management
    dev.uds.icon: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDE2NS40NyAxNjUuNDciPjxkZWZzPjxzdHlsZT4uZHtmaWxsOiMwMzJlNDk7fS5lLC5mLC5ne2ZpbGw6I2ZmZjt9LmYsLmgsLml7c3Ryb2tlLXdpZHRoOjRweDt9LmYsLmgsLmksLmcsLmp7c3Ryb2tlOiNmZmY7fS5mLC5oLC5pLC5qe3N0cm9rZS1saW5lY2FwOnJvdW5kO30uaCwuaSwuantmaWxsOm5vbmU7fS5pLC5qe3N0cm9rZS1saW5lam9pbjpyb3VuZDt9Lmd7c3Ryb2tlLW1pdGVybGltaXQ6MTA7fS5qe3N0cm9rZS13aWR0aDozcHg7fTwvc3R5bGU+PC9kZWZzPjxnIGlkPSJhIi8+PGcgaWQ9ImIiPjxnIGlkPSJjIj48Zz48Y2lyY2xlIGNsYXNzPSJkIiBjeD0iODIuNzMiIGN5PSI4Mi43MyIgcj0iODIuNzMiLz48Zz48cGF0aCBjbGFzcz0iaCIgZD0iTTg0LjYyLDQ1LjcxYzQuOTEsMCw4LjksMy45OCw4LjksOC45Ii8+PHBhdGggY2xhc3M9ImkiIGQ9Ik01OS44Niw2Mi45OWMwLTEyLjY2LDEwLjI2LTIyLjkyLDIyLjkyLTIyLjkyczIyLjkyLDEwLjI2LDIyLjkyLDIyLjkyIi8+PGc+PHBhdGggY2xhc3M9ImUiIGQ9Ik03Ni4yNSw5OC45NWMtLjIxLC4yOS0uNDMsLjQzLS42NSwuNDNzLS40NC0uMS0uNjYtLjI5Yy0uMjItLjE5LS4zMy0uMzgtLjMzLS41NnMuMDktLjM3LC4yNi0uNTZsMS42MS0yLjI2LTIuMTUtLjY5Yy0uNDItLjEzLS42My0uMzUtLjYzLS42NiwwLS4xNywuMDMtLjMyLC4wOS0uNDYsLjExLS40LC4zNS0uNiwuNzItLjYsLjA4LDAsLjIxLC4wMiwuNCwuMDZsMi4yMSwuNzJ2LTIuMzVjMC0uNTcsLjI5LS44NiwuODYtLjg2cy44NiwuMjksLjg2LC44NnYyLjM1bDIuMTUtLjcyYy4xOS0uMDQsLjM1LS4wNiwuNDktLjA2cy4yOSwuMSwuNDYsLjI5Yy4xNywuMTksLjI2LC40NCwuMjYsLjc2cy0uMjEsLjU0LS42MywuNjdsLTIuMTgsLjY5LDEuNjMsMi4yNmMuMTUsLjE3LC4yMywuMzUsLjIzLC41NHMtLjExLC4zOC0uMzMsLjU3Yy0uMjIsLjE5LS40MywuMjktLjY0LC4yOXMtLjQyLS4xNC0uNjMtLjQzbC0xLjY5LTIuMzgtMS42OSwyLjM4WiIvPjxwYXRoIGNsYXNzPSJlIiBkPSJNNjYuNTcsOTguOTVjLS4yMSwuMjktLjQzLC40My0uNjUsLjQzcy0uNDQtLjEtLjY2LS4yOWMtLjIyLS4xOS0uMzMtLjM4LS4zMy0uNTZzLjA5LS4zNywuMjYtLjU2bDEuNjEtMi4yNi0yLjE1LS42OWMtLjQyLS4xMy0uNjMtLjM1LS42My0uNjYsMC0uMTcsLjAzLS4zMiwuMDktLjQ2LC4xMS0uNCwuMzUtLjYsLjcyLS42LC4wOCwwLC4yMSwuMDIsLjQsLjA2bDIuMjEsLjcydi0yLjM1YzAtLjU3LC4yOS0uODYsLjg2LS44NnMuODYsLjI5LC44NiwuODZ2Mi4zNWwyLjE1LS43MmMuMTktLjA0LC4zNS0uMDYsLjQ5LS4wNnMuMjksLjEsLjQ2LC4yOWMuMTcsLjE5LC4yNiwuNDQsLjI2LC43NnMtLjIxLC41NC0uNjMsLjY3bC0yLjE4LC42OSwxLjYzLDIuMjZjLjE1LC4xNywuMjMsLjM1LC4yMywuNTRzLS4xMSwuMzgtLjMzLC41N2MtLjIyLC4xOS0uNDMsLjI5LS42NCwuMjlzLS40Mi0uMTQtLjYzLS40M2wtMS42OS0yLjM4LTEuNjksMi4zOFoiLz48cGF0aCBjbGFzcz0iZSIgZD0iTTg1LjkyLDk4Ljk1Yy0uMjEsLjI5LS40MywuNDMtLjY1LC40M3MtLjQ0LS4xLS42Ni0uMjljLS4yMi0uMTktLjMzLS4zOC0uMzMtLjU2cy4wOS0uMzcsLjI2LS41NmwxLjYxLTIuMjYtMi4xNS0uNjljLS40Mi0uMTMtLjYzLS4zNS0uNjMtLjY2LDAtLjE3LC4wMy0uMzIsLjA5LS40NiwuMTEtLjQsLjM1LS42LC43Mi0uNiwuMDgsMCwuMjEsLjAyLC40LC4wNmwyLjIxLC43MnYtMi4zNWMwLS41NywuMjktLjg2LC44Ni0uODZzLjg2LC4yOSwuODYsLjg2djIuMzVsMi4xNS0uNzJjLjE5LS4wNCwuMzUtLjA2LC40OS0uMDZzLjI5LC4xLC40NiwuMjljLjE3LC4xOSwuMjYsLjQ0LC4yNiwuNzZzLS4yMSwuNTQtLjYzLC42N2wtMi4xOCwuNjksMS42MywyLjI2Yy4xNSwuMTcsLjIzLC4zNSwuMjMsLjU0cy0uMTEsLjM4LS4zMywuNTdjLS4yMiwuMTktLjQzLC4yOS0uNjQsLjI5cy0uNDItLjE0LS42My0uNDNsLTEuNjktMi4zOC0xLjY5LDIuMzhaIi8+PHBhdGggY2xhc3M9ImUiIGQ9Ik05NS42LDk4Ljk1Yy0uMjEsLjI5LS40MywuNDMtLjY1LC40M3MtLjQ0LS4xLS42Ni0uMjljLS4yMi0uMTktLjMzLS4zOC0uMzMtLjU2cy4wOS0uMzcsLjI2LS41NmwxLjYxLTIuMjYtMi4xNS0uNjljLS40Mi0uMTMtLjYzLS4zNS0uNjMtLjY2LDAtLjE3LC4wMy0uMzIsLjA5LS40NiwuMTEtLjQsLjM1LS42LC43Mi0uNiwuMDgsMCwuMjEsLjAyLC40LC4wNmwyLjIxLC43MnYtMi4zNWMwLS41NywuMjktLjg2LC44Ni0uODZzLjg2LC4yOSwuODYsLjg2djIuMzVsMi4xNS0uNzJjLjE5LS4wNCwuMzUtLjA2LC40OS0uMDZzLjI5LC4xLC40NiwuMjljLjE3LC4xOSwuMjYsLjQ0LC4yNiwuNzZzLS4yMSwuNTQtLjYzLC42N2wtMi4xOCwuNjksMS42MywyLjI2Yy4xNSwuMTcsLjIzLC4zNSwuMjMsLjU0cy0uMTEsLjM4LS4zMywuNTdjLS4yMiwuMTktLjQzLC4yOS0uNjQsLjI5cy0uNDItLjE0LS42My0uNDNsLTEuNjktMi4zOC0xLjY5LDIuMzhaIi8+PC9nPjxyZWN0IGNsYXNzPSJqIiB4PSI1Ny41NiIgeT0iODcuNjYiIHdpZHRoPSI1MC40MyIgaGVpZ2h0PSIxNC45MyIgcng9Ii44NyIgcnk9Ii44NyIvPjxnPjxwYXRoIGNsYXNzPSJoIiBkPSJNMzEuMTUsMTAxLjYxYzAtNC45MSwzLjk4LTguOSw4LjktOC45Ii8+PHBhdGggY2xhc3M9ImgiIGQ9Ik0yNC45NCwxMDguNzNjMC0zLjQzLDIuNzgtNi4yMiw2LjIyLTYuMjJzNi4yMiwyLjc4LDYuMjIsNi4yMiIvPjxsaW5lIGNsYXNzPSJpIiB4MT0iNDQuMyIgeTE9Ijg0LjEiIHgyPSI0NC4zIiB5Mj0iMTAyLjg1Ii8+PC9nPjxnPjxwYXRoIGNsYXNzPSJoIiBkPSJNMTM0LjMxLDEwMS42MWMwLTQuOTEtMy45OC04LjktOC45LTguOSIvPjxwYXRoIGNsYXNzPSJoIiBkPSJNMTQwLjUzLDEwOC43M2MwLTMuNDMtMi43OC02LjIyLTYuMjItNi4yMnMtNi4yMiwyLjc4LTYuMjIsNi4yMiIvPjxsaW5lIGNsYXNzPSJpIiB4MT0iMTIxLjE3IiB5MT0iODQuMSIgeDI9IjEyMS4xNyIgeTI9IjEwMi44NSIvPjwvZz48Zz48Y2lyY2xlIGNsYXNzPSJnIiBjeD0iODIuNzgiIGN5PSIxOS40OSIgcj0iNC4zIi8+PGxpbmUgY2xhc3M9ImYiIHgxPSI4Mi43OCIgeTE9IjIxLjIzIiB4Mj0iODIuNzgiIHkyPSI0MC4xOCIvPjwvZz48Zz48cG9seWxpbmUgY2xhc3M9ImkiIHBvaW50cz0iNzkuMjMgMTIxLjUzIDUwLjI5IDEyMS44MyA1MC4yOSA2OC40MiAxMTUuMTggNjguNDIgMTE1LjE4IDEyMS44MyA5MC44NyAxMjEuNTgiLz48cG9seWdvbiBjbGFzcz0iZSIgcG9pbnRzPSI5Mi4wNyAxMTcuNjEgODUuMTMgMTIxLjUzIDkxLjk5IDEyNS41OCA5Mi4wNyAxMTcuNjEiLz48L2c+PC9nPjwvZz48L2c+PC9nPjwvc3ZnPg==
```

```shell
~ > zarf package create -a amd64
~ > zarf package publish -a amd64 zarf-package-external-secrets-amd64-dev.tar.zst oci://registry.gitlab.com/some/registry
2025-05-29 11:25:53 INF loading package path=zarf-package-external-secrets-amd64-dev.tar.zst
2025-05-29 11:25:53 INF pushing package to registry destination=registry.gitlab.com/some/registry/external-secrets:dev architecture=amd64
2025-05-29 11:25:57 ERR PUT "https://registry.gitlab.com/v2/some/registry/external-secrets/blobs/uploads/0eb0936a-c65b-45e5-b55d-5eb3d5c5f1b9?_state=GSPH7keLWWP-1Ou-I_ZMSH1vqPK-wmhkDsn_4W3poTh7Ik5hbWUiOiJ3aWxsL3JlZ2lzdHJ5L2V4dGVybmFsLXNlY3JldHMiLCJVVUlEIjoiMGViMDkzNmEtYzY1Yi00NWU1LWI1NWQtNWViM2Q1YzVmMWI5IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDI1LTA1LTI5VDE2OjI1OjU3LjM5NDA5NjgwM1oifQ%3D%3D&digest=sha256%3A3634d14fa15ccd9abff5b5061faf3184fe675b2f7831953fc5df433950635db3": response status code 200: OK
```

Removing the `dev.uds.icon` annotation,  but keeping the other annotations results in a successful push.

### Severity/Priority

High

### Additional Context
Add any other context or screenshots about the technical debt here.
