### ISSUE TITLE
Choosing 'auth' as ZarfPackageConfig component name will break deploy

### ISSUE THREAD

**Issue by NunoSav** [zarf-dev/zarf#3917]
### Environment
Device and OS: MBP M3, macOS 15.5
App version: 0.56.0

### Steps to reproduce
1. Create `zarf.yaml` and paste:
```yaml
kind: ZarfPackageConfig
metadata:
  name: auth
  description: "Package bug reproduction"

components:
  - name: auth
    required: true
    charts:
      - name: app-template
        version: 3.6.1
        url: https://bjw-s-labs.github.io/helm-charts
        namespace: dti
        releaseName: auth
        valuesFiles:
          - values.yaml
    images:
      - busybox:stable
```
2. Create `values.yaml` in same folder and paste:
```yaml
controllers:
  auth:
    strategy: RollingUpdate
    containers:
      appauth:
        nameOverride: "auth"
        image:
          repository: "busybox"
          tag: "stable"
          pullPolicy: IfNotPresent

service:
  appauth:
    controller: auth
    ports:
      http:
        port: 8080
```
3. Run `zarf package create .`
4. Run either `zarf package deploy <package_name>` or `zarf package inspect values-files <package_name>`

### Expected result
successful output

### Actual Result
>unable to decompress: extracting "/var/folders/h7/hp1475d95m5f5263t8rdv83w0000gn/T/zarf-274063970/components/auth.tar": archive/tar: invalid tar header

### Visual Proof (screenshots, videos, text, etc)
<img width="1232" alt="Image" src="https://github.com/user-attachments/assets/a333d8b2-b5e1-4bf0-8e41-6773e3ef7a2a" />

### Additional Context
Changing the components name to something else fixes the issue.
