### ISSUE TITLE
Repo name mismatch after mutation

### ISSUE THREAD

**Issue by oscar-izval** [zarf-dev/zarf#3918]
### Environment
Device and OS: macOS (ARM)
App version: v0.56.0
Kubernetes distro being used: CAPI v1.32.3
Other: N/A

### Steps to reproduce
1. Start by deploying `example/argocd`. This works just fine and the argo app is synced and healthy
2. Add one extra app under `examples/argocd/apps/values.yaml`. Note than I'm targeting a private repo and a specific branch.
```yaml
  - name: my-app
    namespace: argocd
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: default
    sources:
      - repoURL: 'https://github.com/<org>/<private-repo>.git'
        path: kustomize/overlays/dev/argocd/apps
        targetRevision: my-branch
    syncPolicy:
      automated: { }
    destination:
      server: https://kubernetes.default.svc
```
3. Add the private repo in zarf.yaml. I'm using SSH here as https doesn't work for me (https://github.com/zarf-dev/zarf/issues/3915#issuecomment-2983532028)
```diff
diff --git a/examples/argocd/zarf.yaml b/examples/argocd/zarf.yaml
index 8c548465..33359798 100644
--- a/examples/argocd/zarf.yaml
+++ b/examples/argocd/zarf.yaml
@@ -32,6 +32,7 @@ components:
           - apps/values.yaml
     repos:
       - https://github.com/stefanprodan/podinfo.git
+      - ssh://git@github.com/<org>/<private-repo>.git
     images:
       - ghcr.io/stefanprodan/podinfo:6.4.0
     actions:
```
4. Create and deploy the package with `zarf package create --architecture amd64` and `zarf package deploy zarf-package-argocd-amd64.tar.zst`.
5. When the repo is pushed to gitea, it'll get a name like `zarf-git-user/<private-repo>-1959568821` but the argo app will get a different one: `zarf-git-user/<private-repo>-3204222913.git`

### Expected result
The mutation of the argo app should point to the correct repo.
### Actual Result
The argo apps point to a missing repo and therefore fail to deploy anything.
### Visual Proof (screenshots, videos, text, etc)
I'm using real but anonymized values in the steps to reproduce but can provide more details if needed.
### Severity/Priority
Currently a blocker for us to use zarf. Feels like a pretty standard use-case so I'll say `high` priority.
### Additional Context
- I disabled the zarf agent for the argo app and manually pointed to the right repo, everything works that way.
- I thought the way we reference the repo in `zarf.yaml` might be affecting the id calculation, but could't use the standard HTTPS domain because of the other issue I mentioned above. Targeting specific branches, tags, using SSH etc. produces different repos in gitea, but the mutation performed in the Argo app remains constant (I think this is important).

Thanks!
