### ISSUE TITLE
sourceRepos of an argocd project doesn't get updated by zarf

### ISSUE THREAD

**Issue by sepauli** [zarf-dev/zarf#3952]
### Environment
Device and OS: Ubuntu 24.04
App version: v0.57.0
Kubernetes distro being used: RKE2 v1.33.1+rke2r1

### Steps to reproduce
We deploy the following zarf package
```
---
kind: ZarfPackageConfig
metadata:
  name: argocd
  description: Example ArgoCD
  architecture: amd64
components:
  - name: argocd
    required: true
    charts:
      - name: argo-cd
        version: 8.1.1
        #version: 5.54.0
        namespace: argocd
        url: https://argoproj.github.io/argo-helm
        releaseName: argocd
        valuesFiles:
          - packages/argo-cd/values.yaml
    images:
      - ecr-public.aws.com/docker/library/redis:7.2.8-alpine
      - ghcr.io/dexidp/dex:v2.43.1
      - quay.io/argoproj/argocd:v3.0.6
      # Cosign artifacts for images - argocd
      - ghcr.io/dexidp/dex:sha256-0881d3c9359b436d585b2061736ce271c100331e073be9178ef405ce5bf09557.sig
      - quay.io/argoproj/argocd:sha256-a45307e2695d0fd93713e3d211b71086ac75a85dc8afbb28a249bdc4b3b0b2b9.sig
      - quay.io/argoproj/argocd:sha256-a45307e2695d0fd93713e3d211b71086ac75a85dc8afbb28a249bdc4b3b0b2b9.att
  - name: argocd-apps
    required: true
    charts:
      - name: argocd-apps
        version: 2.0.2
        namespace: argocd
        url: https://argoproj.github.io/argo-helm
        releaseName: argocd-apps
        valuesFiles:
          - packages/argo-cd/apps.yaml
    repos:
      - https://gitlab.example.com/argocd-applications.git
      - https://gitlab.example.com/application-helm-values.git
```
With this zarf package we want to install argocd including all dependencies.
Because we want to use gitops within our air-gapped environment, we want git to be our source of truth.
For this reason, we have defined all applications as manifests in the repo `https://gitlab.example.com/argocd-applications.git` 
The applications then use the helm configuration defined in the repo `https://gitlab.example.com/application-helm-values.git`
The idea is that argocd updates then itself with the right configuration from git

The Application manifest looks like this
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: guestbook
spec:
  project: my-project
  sources:
    - repoURL: 'https://gitlab.example.com/argocd-applications.git'
      chart: argo-cd
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/helm-values/argo-cd/values.yaml
    - repoURL: 'https://gitlab.example.com/application-helm-values.git'
      targetRevision: HEAD
      ref: values
<SNIP>
```
The URLs which are defined in this manifest gets then overriden by zarf with the correct URL in the zarf-gittea.
So this works fine.

In addition to the applications, we also define various projects with permissions.
```
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: my-project
  sourceRepos:
    - 'zarf-docker-registry.zarf.svc.cluster.local:5000'
    - https://gitlab.example.com/argocd-applications.git
    - https://gitlab.example.com/application-helm-values.git
  destinations:
    - namespace: '!default'
      server: '*'
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - description: Admin privileges
      groups:
        - admin
      name: admin
      policies:
        - 'p, proj:my-project:admin, applications, *, my-project/*, allow'
  orphanedResources:
    warn: false
```
Here is the problem.
The `sourceRepos` are not overridden by zarf, which means that the applications have no authorization to access the git repos from the corresponding project and the old entries like ` https://gitlab.example.com/application-helm-values.git` are still there.
So the applications cannot be deployed.

### Expected result
The URLs of the repositories in the `sourceRepos` section of an `AppProject` should also be overridden like the `repoURL` in the `Application` manifest

### Actual Result
The `sourceRepos` section of an `AppProject` does not get overridden by zarf
